### PR TITLE
Run phpcs, php-cs-fixer, phpstan, coverage, versions as Php8.1

### PR DESCRIPTION
**Pull request by oleibman**
They all run under Php7.4 in Github. 7.4 is EOL. We still have to run unit tests in 7.4, but I think it's time to move the tools. Note that we cannot currently run Phpstan in 8.2 because of https://github.com/phpstan/phpstan/issues/8629.

This is:

- [ ] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests

Checklist:

- [ ] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [ ] New unit tests have been added
- [ ] Code style is respected
- [ ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change and a link to the pull request if applicable
- [ ] Documentation is updated as necessary

### Why this change is needed?

Provide an explanation of why this change is needed, with links to any Issues (if appropriate).
If this is a bugfix or a new feature, and there are no existing Issues, then please also create an issue that will make it easier to track progress with this PR.

### CODE REVIEW

**Comment by oleibman** [comment]
Same error for Coverage with Php 8.0. Trying 7.4.

**Comment by oleibman** [comment]
@MarkBaker @PowerKiKi Any idea why Coverage results upload should fail using Php 8.1/8.0 but succeed with Php 7.4? Message for 8.1/8.0 documented above.

That error notwithstanding, is this change (with or without Coverage change) a bad idea? Good idea? It depends?

**Comment by MarkBaker** [comment]
> @MarkBaker @PowerKiKi Any idea why Coverage results upload should fail using Php 8.1/8.0 but succeed with Php 7.4? Message for 8.1/8.0 documented above.
 
No idea why the upload should be failing, other than perhaps the underlying version of guzzle or curl.

> That error notwithstanding, is this change (with or without Coverage change) a bad idea? Good idea? It depends?

Good idea, because we'll be dropping PHP 7.4 support in a few months time

**Comment by MarkBaker** [comment]
https://github.com/scrutinizer-ci/ocular/issues/62

**Comment by oleibman** [comment]
Thank you. It took a couple of tries to get it right, but now appears to be working.

**Review by PowerKiKi — APPROVED** [review]

**Pull request merged**
