### PR TITLE
fix warning when open xlsx file with thumbnail

### LINKED ISSUE #2516: When open xlsx with thumbnail it has some warning.
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
It can open xlsx with thumbnails files without any warning. (like phpoffice/phpspreadsheet 1.16.0)

### What is the current behavior?
it warning. stacktrace look likes
```
[2022-01-21 12:39:57] local.ERROR: simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found {"userId":6,"exception":"[object] (ErrorException(code: 0): simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found at /path/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:126)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /path/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php(126): simplexml_load_string()
#2 /path/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php(232): PhpOffice\\PhpSpreadsheet\\Reader\\Xlsx->loadZip()
...
```

### What are the steps to reproduce?
[file_with_thumbails.xlsx](https://ishare.in.th/tmp/PhpSpreadsheet-2516/file_with_thumbails.xlsx)
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;

$reader = IOFactory::createReader('Xlsx');
$reader->listWorksheetInfo('file_with_thumbails.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.4.9
phpoffice/phpspreadsheet 1.21.0

### PR DESCRIPTION
**Pull request by mix5003**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?
this should fix #2516. by not try to open thumbnail as xml

### CODE REVIEW

**Comment by oleibman** [comment]
Your test file is very large, and I am having trouble reading it because of that, but not because of the thumbnail file. I am going to upload another, much smaller file. Do you see the same warning message when you read it? I don't see any warning messages with several different versions of PhpSpreadsheet. I do see a bit of a problem - the thumbnail fail is basically ignored rather than used when, for example, saving a copy of the original - but that's a different problem that will need a different solution.
[issue.2516b.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7921107/issue.2516b.xlsx)

**Comment by mix5003** [comment]
i updated test files. 

>  I don't see any warning messages with several different versions of PhpSpreadsheet

it should show warning because this piece of code try to call `loadZip` every files in `_rels/.rels` link
https://github.com/PHPOffice/PhpSpreadsheet/blob/aa29947e0d32716dcca97d3245b5269c059abc92/src/PhpSpreadsheet/Reader/Xlsx.php#L175-L190
and `loadZip` try to open it as XML
https://github.com/PHPOffice/PhpSpreadsheet/blob/aa29947e0d32716dcca97d3245b5269c059abc92/src/PhpSpreadsheet/Reader/Xlsx.php#L122-L133

in this case `docProps/thumbnail.wmf` is not xml. so it should warning like my original issue 
`simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found`

but if you don't see warning message i think it up to default error_reporting level. if default error_reporting is E_ERROR (not show warning). it will not show anything. should i add `error_reporting(E_WARNING);` in test case? or do you have anyway to  test it properly?

**Comment by oleibman** [comment]
Aha! Thank you for the explanation. The warning messages you see are when you execute the `listWorksheetNames` method, and I didn't see them because I was executing the `load` method. It seems to me that the `listWorksheetInfo` method should have the same problem as `listWorksheetNames`, and that your fix for one should also fix the other. Can you please add an additional test for `listWorksheetInfo`?

**Comment by mix5003** [comment]
added test for `listWorksheetInfo`

**Comment by oleibman** [comment]
Thank you for your contribution.

**Pull request merged**
