### PR TITLE
fix: Load tables when flag IReader::READ_DATA_ONLY is used

### PR DESCRIPTION
**Pull request by kevin-verschaeve**
Abstract

This PR adds the loading of the named tables when using the `IReader::READ_DATA_ONLY` flag

This is:

- [x] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests

Checklist:

- [x] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [x] New unit tests have been added
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change and a link to the pull request if applicable
- [ ] Documentation is updated as necessary

### Why this change is needed?

When loading a spreadsheet, using the flag `IReader::READ_DATA_ONLY` to be faster and use less memory, I encountered an issue.

The CalculationEngine tried to resolve a cell formula. That formula was refering to a named table. Named table are not loaded because of the `IReader::READ_DATA_ONLY` flag.

I feel that, when using that flag, we should either:
 - not try to resolve formulas at all
 - or: fully resolve them, which means loading named tables

For information, we did not notice any performance degradation when loading the named table vs not doing it, at least of the large spreadsheet files we are using.

### CODE REVIEW

**Comment by oleibman** [comment]
I think you are correct that Tables should be read even with dataOnly. Can you please add a unit test that demonstrates that your change works as desired?

**Comment by kevin-verschaeve** [comment]
cool !
sure, I'll try to do it next week.

Thanks

**Comment by kevin-verschaeve** [comment]
I've added a test, please tell me if it seems good for you

**Comment by oleibman** [comment]
Looks good. I will try to merge this in a day or two.

**Comment by oleibman** [comment]
Thank you for your contribution.

**Pull request merged**
