### PR TITLE
Remove + From Mode in BaseWriter

### PR DESCRIPTION
**Pull request by oleibman**
BaseWriter openFileHandle opens its output file with mode `wb+`. We don't appear to attempt any reads on the file after it is opened in write mode, so `wb` should be sufficient. This may have been a factor in the need for PR #2326, and is likely to be responsible for issue #2372.

This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### CODE REVIEW

**Comment by oleibman** [comment]
@MarkBaker @PowerKiKi - I have put this in draft form because I want another opinion. This is a really simple change, it passed all the unit tests, and I can't find any reason for the unusual mode declaration in the first place. But perhaps there's some history behind it, or my search was flawed. Do you know of any reason not to move this forward?

**Comment by MarkBaker** [comment]
My recollection was that it was necessary when running PHP on Windows in the early PHP5 releases, otherwise binary content such as embedded images couldn't load

**Comment by oleibman** [comment]
That's good - I do almost all my testing on Windows, so, if that was still a problem, I'd see it. I'll double-check all the sample outputs before marking this ready.

**Comment by PowerKiKi** [comment]
I am not aware of problems that this change could cause... :shrug:

**Comment by oleibman** [comment]
I see no problems created in the sample files, so have marked this ticket as ready.

**Pull request merged**
