### PR TITLE
Fix issue #1364: Removing last row incorrect behavior

### PR DESCRIPTION
**Pull request by TimGa**
This is:

```
- [X] a bugfix
- [ ] a new feature
```

Checklist:

- [X] Changes are covered by unit tests
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [X] CHANGELOG.md contains a short summary of the change
- [x] Documentation is updated as necessary

### Why this change is needed?
This PR fixes [#1364](https://github.com/PHPOffice/PhpSpreadsheet/issues/1364) Removing last row incorrect behavior

Description:
`$highestRow = $this->getHighestDataRow();` was calculated after `$this->getCellCollection()->removeRow($pRow + $r);` - this is the root reason for incorrect rows removal because removing last row will change '$this->getHighestDataRow()' value, but removing row from the middle will not change it. So, removing last row causes incorrect `$highestRow` value that is used for wiping out empty rows from the bottom of the table:
```php
for ($r = 0; $r < $pNumRows; ++$r) {
    $this->getCellCollection()->removeRow($highestRow);
    --$highestRow;
}
```
To prevent this incorrect behavior I've moved highest row calculation before row removal.
But this still doesn't solve another problem when trying remove non existing rows: in this case the code above will remove `$pNumRows` rows from below of the table, e.g. if `$highestRow=4` and `$pNumRows=6`, than rows 4, 3, 2, 1, 0, -1 will be deleted. Obviously, this is not good, that is why I've added `$removedRowsCounter` to fix this issue.
And finally, moved Exception to early if statement to get away from unnecessary 'if-else'.

### CODE REVIEW

**Comment by TimGa** [comment]
Hi, @PowerKiKi 
Could you please review this PR?

**Comment by minhtranahri** [comment]
Hi @TimGa , i think just remove this code is enough
```
for ($r = 0; $r < $pNumRows; ++$r) {
    $this->getCellCollection()->removeRow($highestRow);
    --$highestRow;
}
```

**Comment by TimGa** [comment]
Hi @minhtranahri , you are right, removing this part of code will solve the issue, but somebody wrote it for some reason, that is why I decided to keep it. This part of code could be used for deleting cache stuff or some other implicit actions i don't know. So I decided to fix this issue without removing existing lines of code.

**Comment by minhtranahri** [comment]
Hi @TimGa, thanks for clarifying and being careful. Very appreciate!

**Comment by PowerKiKi** [comment]
Thank you for the well crafted PR and your patience.

**Pull request merged**
