### PR TITLE
 Fix For #1509

### PR DESCRIPTION
**Pull request by oleibman**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [x] Documentation is updated as necessary

### Why this change is needed?
User expected no CSV enclosures after $writer->setEnclosure(''),
which had been changed to be consistent with $reader->setEnclosure('').
Writer will now omit enclosures after code above; no change to Reader.
Tests have been added for this condition.

### CODE REVIEW

**Comment by MarkBaker** [comment]
Thank you for the quick resolution to the issue with setting empty CSV enclosures

**Comment by atreitsma** [comment]
@MarkBaker could you be so kind and make this a new release so we don't need workarounds to make **CSV Enclosure** working as expected again in `Maatwebsite/Excel` ? since it uses the latest release... thanks in advance!

**Comment by MarkBaker** [comment]
I really want to get the changes that I'm doing rewriting named ranges/formulae completed before doing a new release (perhaps another week or two of work), because the next steps that I'm planning after that could lead to some bc breaks, which would require a new 2.0.0 release.
Is it possible for you to work with dev-master for that time? Or does the Laravel wrapper restrict you to tagged releases?

**Comment by SudoGetBeer** [comment]
> I really want to get the changes that I'm doing rewriting named ranges/formulae completed before doing a new release (perhaps another week or two of work), because the next steps that I'm planning after that could lead to some bc breaks, which would require a new 2.0.0 release.
> 
> Is it possible for you to work with dev-master for that time? Or does the Laravel wrapper restrict you to tagged releases?

You can just use  "phpoffice/phpspreadsheet": "1.12.0", in composer and everything works 😉

**Comment by atreitsma** [comment]
Even though @MarkBaker just tagged a new release, the requirements changed for Guzzle 6 -> 7 and that is a no go (it's like domino, now with Google API) ... so no solution to update to latest tagged releases and that indeed leaves the option as stated by @SudoGetBeer open as final solution for now. I do understand the choice @MarkBaker to aim for a bigger release... and will keep an eye out on package updates so this will integrate nicely again.

**Pull request merged**
