### PR TITLE
#928: fix for worksheet lookup for worksheets with spaces in the title

### PR DESCRIPTION
**Pull request by azine**
This is a PR for #928

```
- [ x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [x] CHANGELOG.md contains a short summary of the change
- [x] Documentation is updated as necessary

### Why this change is needed?
see #928 and #462

### CODE REVIEW

**Comment by azine** [comment]
anyone?!

**Comment by azine** [comment]
that "stale bot" is very annoying!

**Comment by PowerKiKi** [comment]
Thank you for your patience and your PR, I'll merge this shortly

**Comment by PowerKiKi** [comment]
Merged in 98a1f0a8cf9f9ca5e32840718df6bfc1555463fa

**Pull request closed without merging**
