### PR TITLE
Fix for #2149 / Read data validations for drop down list in another sheet.

### PR DESCRIPTION
**Pull request by otargetj2s**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?
This modification makes it possible to read the drop-down lists linked to other sheets. 
See issue #2149

### CODE REVIEW

**Comment by oleibman** [comment]
Without actually commenting on the substance of your change, it appears that your commit merely adds a block of commented out code. Did you mean to remove the comment marks?
Also, is it possible to write a unit test which will show that your change operates as desired?

**Comment by otargetj2s** [comment]
> Without actually commenting on the substance of your change, it appears that your commit merely adds a block of commented out code. Did you mean to remove the comment marks?
> Also, is it possible to write a unit test which will show that your change operates as desired?

Sorry, i uncommented the code block. It was for test purpose.
I never wrote any unit tests for PHP but i would be thankful to anyone to do it.

**Comment by otargetj2s** [comment]
> > Without actually commenting on the substance of your change, it appears that your commit merely adds a block of commented out code. Did you mean to remove the comment marks?
> > Also, is it possible to write a unit test which will show that your change operates as desired?
> 
> Sorry, i uncommented the code block. It was for test purpose.
> I never wrote any unit tests for PHP but i would be thankful to anyone to do it.

Finally, i have created the unit test and validated it successfully.

**Comment by otargetj2s** [comment]
I finished. I don't make any more changes.

**Comment by MarkBaker** [comment]
I've added some more assertions to verify that the list address is correctly loaded with the worksheet name, and resolved the phpstan issue

**Comment by MarkBaker** [comment]
Thank you for this contribution: it may be reworked a bit as we work with the handling of namespaces in Xlsx files

**Comment by otargetj2s** [comment]
> Thank you for this contribution: it may be reworked a bit as we work with the handling of namespaces in Xlsx files

I'm happy to have been able to contribute to this project.
Thank you also to you.

**Comment by poojithamiryala** [comment]
When can we expect this fix to be released?

**Comment by otargetj2s** [comment]
Hello,

I hoped to have it as soon as possible, but I found a solution of waiting.
This bug dates from 2018.
As you prefer.


Olivier TARGET

**Pull request merged**
