### PR TITLE
Refactor xlsx writer

### LINKED ISSUE #1911: Error when saving an Xlsx file (with images) with the same name!
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
An xlsx file with images can be saved several times with the same name, without errors occurring.

### What is the current behavior?
When we try to save a file with images, that already exists with the same name, an error occurs.
```
PHP Fatal error:  Uncaught PhpOffice\PhpSpreadsheet\Writer\Exception: File zip://C:\Users\diogo\Documents\PhpSpreadsheet\test.xlsx#xl/media/54b0c99f8d2c2a408c3a8abee180cd941.png does not exist in C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php:198
Stack trace:
#0 C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php(126): PhpOffice\PhpSpreadsheet\Writer\Xlsx\ContentTypes->getImageMimeType()
#1 C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx.php(216): PhpOffice\PhpSpreadsheet\Writer\Xlsx\ContentTypes->writeContentTypes()
#2 C:\Users\diogo\Documents\PhpSpreadsheet\BugReport.php(30): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save()
#3 {main}
  thrown in C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php on line 198
```

### What are the steps to reproduce?
1) Create an Xlsx file with images.
2) Save this file.
3) Load the file;
4) Save it again with the same name.
 
Note: I'm using the same code used by @PowerKiKi  in this comment [https://github.com/PHPOffice/PhpSpreadsheet/issues/544#issuecomment-427643848](https://github.com/PHPOffice/PhpSpreadsheet/issues/544#issuecomment-427643848). The unique difference is that I'm saving the second Xlsx file with the same name as the first file.

```php
<?php
require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Worksheet\MemoryDrawing;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();

// Generate an image
$gdImage = imagecreatetruecolor(250, 30);
$textColor = imagecolorallocate($gdImage, 255, 255, 255);
imagestring($gdImage, 4, 5, 5, 'Created with PhpSpreadsheet', $textColor);

// Add a drawing to the worksheet
$drawing = new MemoryDrawing();
$drawing->setImageResource($gdImage);
$drawing->setWorksheet($spreadsheet->getActiveSheet());

$writer = new Xlsx($spreadsheet);
$writer->save('test.xlsx');

$reloaded = IOFactory::load('test.xlsx');

$reloaded->getActiveSheet()->setCellValue('D5', 'foo');

$writer = new Xlsx($reloaded);
$writer->save('test.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: v1.17.1
PHP: v7.4.13;

### PR DESCRIPTION
**Pull request by ccrims0n**
Fix #1911 

* Move the writer part to the end of the `save()`

This is:
```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### CODE REVIEW

**Comment by ccrims0n** [comment]
@MarkBaker Can someone help with reviewing this PR

**Comment by oleibman** [comment]
Can you please make a minor change to your test? Rather than editing your test file in place, copy it to the temporary directory (file_get_contents followed by file_put_contents should suffice), run your test against the temporary copy, and delete the temporary copy at the end. The difference between this and your existing test is that, if something goes wrong, we don't lose the good copy of the test file.

**Comment by ccrims0n** [comment]
@oleibman perfect. will make the changes.

**Comment by oleibman** [comment]
Please unlink the temporary file at the end of your test, and I think this will be good to go.
@MarkBaker and @PowerKiKi , after this last change is made, I would like to proceed with merging this change. Since it will be my first time doing that (I am reviewing one other), I just want you to alert you about that in case something goes amiss.

**Comment by PowerKiKi** [comment]
> in case something goes amiss

As long as GitHub is all green, merging should be fine. But I'll keep an eye open...

**Pull request merged**
