### PR TITLE
Cell Coordinate splitRange doesn't support space delimeter

### PR DESCRIPTION
**Pull request by mcouillard**
This is: new feature to support spaced coordinates instead of just comma delimited lists. Specific to the splitRange() method.
Issue #1457 

```
- [ ] a bugfix
- [X] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [X] CHANGELOG.md contains a short summary of the change
- [X] Documentation is updated as necessary

### Why this change is needed?
Excel can save protection ranges as a spaced list instead of just a comma list.

### CODE REVIEW

**Comment by MarkBaker** [comment]
You're right that a space can appear in a range definition; but it isn't simply an alternative for a comma.
Both space and comma are operators in a range definition:
 - A comma is the Union operator (combines two references into a single reference)
 - A space is the Intersection operator (returns a reference to the intersection of two ranges)
So I need to take a much more detailed look at how well PHPSpreadsheet handles this difference when it is used.

**Comment by mcouillard** [comment]
That makes more sense! My solution didn't feel optimal and I couldn't find the right doc from Microsoft or about OpenXML to determine what these spaces here actually meant.

I appreciate your help.

**Comment by MarkBaker** [comment]
He, yes! It's pretty obscure: simple example is to fill cells A1 to C3 with the values 1 to 9, then to have a couple of formulae: `=SUM(A1:B2,B2:C3)` and `=SUM(A1:B2 B2:C3)` and look at the different results.
I'll try putting some tests together tonight to see what the effects will be.

**Comment by oleibman** [comment]
Superseded by PR #4580. Removing stale label, leaving closed.

**Pull request closed without merging**
