### PR TITLE
Move Gridlines from Chart to Axis

### PR DESCRIPTION
**Pull request by oleibman**
This could, I hope, be my last major change to Chart for a while. When I first noticed this problem, I thought it would be a breaking change. However, although this change establishes some deprecations, I don't think it breaks anything. Major and minor gridlines had only been settable by the Chart constructor. This PR moves them where they belong, to Axis (eexisting Chart constructor code will still work). This allows them to be specified from both X and Y axis.

Chart is now entirely covered except for 2 statements, one deprecated and one that I just can't figure out. 99.71% for Charts, 88.96% overall. All references to the Chart directory in Phpstan baseline are eliminated.

This is:

```
- [x] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests
```

Checklist:

- [x] Changes are covered by unit tests
  - [x] Changes are covered by existing unit tests
  - [x] New unit tests have been added
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

Provide an explanation of why this change is needed, with links to any Issues (if appropriate).
If this is a bugfix or a new feature, and there are no existing Issues, then please also create an issue that will make it easier to track progress with this PR.

### CODE REVIEW

**Comment by MarkBaker** [comment]
You've done a lot of great work with charts, and I think when you merge this PR I'll do a 1.24 release. Then it'll be time for renaming master as 1.x and enabling the 2.x branch... I still need to document all the deprecations and changes for 2.0, so it isn't quite ready yet for an alpha release, so we'll still be working with master/1.x for at least one more release (I'll keep 2.x in synch)

**Comment by oleibman** [comment]
I probably won't merge till the weekend. My usual pattern with these changes has been to push the code and maybe some samples, then add some unit tests. I'm still working on the unit tests for this one.

**Comment by MarkBaker** [comment]
> I probably won't merge till the weekend. My usual pattern with these changes has been to push the code and maybe some samples, then add some unit tests. I'm still working on the unit tests for this one.

No hurry, I was just giving you a "heads up"; but with all the works you've done to improve charts, and with my speed/memory updates, I'll do another release soon (especially if I can get structured references working)

**Comment by oleibman** [comment]
@MarkBaker It's merged now. Good luck with the release.

**Pull request merged**
