### PR TITLE
Calculation engine array formulae initial work

### PR DESCRIPTION
**Pull request by MarkBaker**
This is:

```
- [ ] a bugfix
- [X] a new feature
```

Checklist:

- [X] Changes are covered by unit tests
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

Initial support for reading/writing array formulae with the Xlsx Reader/Writer

Work to allow setting array formulae from userland code looks like it will create a BC break. It requires extra arguments for the Cell `setValue()` and `setValueExplicit()` methods - the equivalent of pressing Ctrl-Enter when entering an array formula in MS Excel - (unless I can come up with some creative alternative, like executing the formula at the point when it is set to identify if it is an array formula or not; and if so, what the spillage cell range should be); and these additional arguments must be passed to the Cell Binder creating a BC break for the BinderInterface.

### CODE REVIEW

**Comment by oleibman** [comment]
Unrelated to this PR, I have come upon something that could be categorized as a security problem. I do not see how to fix it for the moment, and, more importantly, I am not sure how to report it. What would be the best way to communicate about it?

**Comment by MarkBaker** [comment]
EMail me (mark at angel-demon dot eu)

**Comment by oleibman** [comment]
550: Unrouteable address

**Comment by MarkBaker** [comment]
Sorry, it was  demon-angel, not angel-demon

**Pull request closed without merging**
