### PR TITLE
More RTL Support for Xlsx/Html Comments

### PR DESCRIPTION
**Pull request by oleibman**
Following up from PR #4006. There is an additional RTL property available. It controls the placement of bidirectional neutral characters (mainly punctuation), as opposed to strong (alphabetic characters) or weak (numeric characters), especially at the beginning or end of a line. The new Comment property textboxDirection will be used for that purpose.

In a discussion in issue #4004 following the implementation of the PR, the comment was mixed RTL and LTR, and this led to some formatting problems. The user was able to overcome these with the timely insertion of Unicode directional control characters, but it would be preferable to have it happen automatically, which this change will permit. However, the use of these control characters cannot be entirely done away with. In the new test case, if one of the all-English lines ended with, say, a colon, it would not display correctly; LRM (left-to-right mark) after the colon would be needed. Likewise, one or two of the comment lines with mixed RTL and LTR (discussed in the issue) is not formatted correctly, and might require LRO/PDF or equivalent.

This is:

- [ ] a bugfix
- [x] a new feature
- [ ] refactoring
- [ ] additional unit tests

Checklist:

- [ ] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [x] New unit tests have been added
- [x] Code style is respected
- [ ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change and a link to the pull request if applicable
- [ ] Documentation is updated as necessary

### Why this change is needed?

Provide an explanation of why this change is needed, with links to any Issues (if appropriate).
If this is a bugfix or a new feature, and there are no existing Issues, then please also create an issue that will make it easier to track progress with this PR.

### CODE REVIEW

**Comment by berberon** [comment]
How would a line of code using textboxDirection  look like?

**Comment by berberon** [comment]
I'm sorry,

I don't understand what you means by "See testIssue4004td in the new test members that are part of this PR."

**Comment by oleibman** [comment]
There is a clickable "Files Changed" items at the top of this page. If you click on that, you'll see all the code that is changing with this PR. At the very bottom of the page, you'll see CommentAlignmentTest.php, and that has a method testIssue4004td, which demonstrates the use of setTextboxDirection.

**Comment by berberon** [comment]
Hi,

I really appreciate your patience and your willingness to explain. It's truly valued.

So instead of  :

```
	$objPHPExcel->getActiveSheet()->getComment('A1')->getText()->createTextRun(**"\u{202E}"** . $SettingsStamp);
	$objPHPExcel->getActiveSheet()->getComment('A1')->setAlignment(Alignment::HORIZONTAL_RIGHT);

```
I will be able to  do :

```
	$objPHPExcel->getActiveSheet()->getComment('A1')->getText()->createTextRun("\u{202E}" . $SettingsStamp);
	$objPHPExcel->getActiveSheet()->getComment('A1')->setAlignment(Alignment::HORIZONTAL_RIGHT);
        $objPHPExcel->getActiveSheet()->getComment('A1')->**setTextboxDirection(Comment::TEXTBOX_DIRECTION_RTL);**

```

I have been waiting years for such an option and it will certainly be appreciated by out excel users :)

**Pull request merged**
