### PR TITLE
More Display Options for Chart Axis and Legend

### LINKED ISSUE #3414: Change the color of the Title and data
Hello, 
I want to change the color of the white title and the vertical data on the left, and the data on the x axis, but it does not allow me to change. Could you help me with the code.
datacolor

### PR DESCRIPTION
**Pull request by oleibman**
Fix #3414. There had been no way to color the text used for the data points on an axis. It is now supported via a new AxisText class, which derives from Properties, and has FillColor and effects (glow/shadow/softEdges) properties. The code changes in chart sample 33_Chart_create_scatter2 illustrate usage.

Similarly, following a wide-ranging discussion in #3433, there was no way to add a border to a Legend. This change allows the setting of border color and fill color, and likewise adds an AxisText object to Legend, permitting the addition of colors and effects to the Legend text.

This is:

- [ ] a bugfix
- [x] a new feature
- [ ] refactoring
- [ ] additional unit tests

Checklist:

- [ ] Changes are covered by unit tests
  - [x] Changes are covered by existing unit tests
  - [x] New unit tests have been added
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change and a link to the pull request if applicable
- [ ] Documentation is updated as necessary

### Why this change is needed?

Provide an explanation of why this change is needed, with links to any Issues (if appropriate).
If this is a bugfix or a new feature, and there are no existing Issues, then please also create an issue that will make it easier to track progress with this PR.

### CODE REVIEW

**Comment by oleibman** [comment]
Not concerned with Scrutinizer "complexity" complaint.

**Comment by ByronSilvaOlvera** [comment]
I am going to try

**Comment by ByronSilvaOlvera** [comment]
I'm testing, but I don't get the new class.

This class

$xAxisText = new AxisText();
$xAxisText->getFillColorObject()->setValue('00FF00')->setType(ChartColor::EXCEL_COLOR_TYPE_RGB);
$xAxis->setAxisText($xAxisText);

I already actulize composer update but it does not download the new

**Comment by oleibman** [comment]
@ByronSilvaOlvera you need to install from master.
```
composer require phpoffice/phpspreadsheet:dev-master
```

**Pull request merged**
