### PR TITLE
NULL value handling in PRODUCT() Excel function

### PR DESCRIPTION
**Pull request by MarkBaker**
This is:

```
- [X] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests
```

Checklist:

- [X] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [X] New unit tests have been added
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

Resolve [Issue #2833](https://github.com/PHPOffice/PhpSpreadsheet/issues/2833), PhpSpreadsheet mishandles NULL in PRODUCT() function

### CODE REVIEW

**Comment by oleibman** [comment]
@MarkBaker Are you sure this solution is correct? Shouldn't PRODUCT(12.5, null, 2.5) be 31.25, not 0?

**Comment by MarkBaker** [comment]
Hmmm, yes. You're correct. my bad

**Comment by MarkBaker** [comment]
Do you want to sanity check me on [PR #2835](https://github.com/PHPOffice/PhpSpreadsheet/pull/2835)

**Comment by oleibman** [comment]
That change looks good.

**Pull request merged**
