### PR TITLE
Using setSelectedCells with freezePane in Xlsx writer

### PR DESCRIPTION
**Pull request by LoranRendel**
Issue #404

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Would you be able to add tests to cover that writer, and possibly others ? A good example for this case would be something similar to `\PhpOffice\PhpSpreadsheetTests\Functional\EnclosureTest`

**Comment by LoranRendel** [comment]
Please check if anything wrong.

**Comment by LoranRendel** [comment]
Please review my request.

**Comment by PowerKiKi** [comment]
If you change your test value from `$selectedCell = 'A1';` to `$selectedCell = 'A2';`, then the tests will fail. It seems the patch is not working as expected. Would you be able to debug it further ?

**Comment by oleibman** [comment]
Superseded by PR #3841.

**Pull request closed without merging**
