### PR TITLE
Add .editorconfig file

### PR DESCRIPTION
**Pull request by chapeupreto**
This PR adds `.editorconfig` file.

See `https://editorconfig.org/` for further details.

### CODE REVIEW

**Comment by MarkBaker** [comment]
Editor configuration files are personal, and should not be part of the repository; that file should be listed in a gitignore instead

**Comment by chapeupreto** [comment]
Hi @MarkBaker. Maybe you're getting it wrong.

The `.editorconfig` file *is not* a personal file. 

As the documentation on https://editorconfig.org/ says: 

> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

This file *must* not be listed in `.gitignore`

Many projects are using a `.editorconfig` file, e.g., https://github.com/spatie/laravel-data/blob/main/.editorconfig

What do you think?

**Comment by MarkBaker** [comment]
I stand corrected, and have taken advice on this. While not universal, the overall recommendation is to include it in the repo, but can you “export-ignore” it in .gitattributes? It's for developers/contributors, not for end users of the library.

**Comment by chapeupreto** [comment]
Sure! Done!

**Comment by MarkBaker** [comment]
Thank you, and thank you for enlightening me about `editorconfig` files

**Comment by chapeupreto** [comment]
Thanks for everything you do for the PHP community.

**Pull request merged**
