### PR TITLE
Fix copying a spreadsheet

### LINKED ISSUE #1483: Spreadsheet copy removes worksheets from source
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

I am creating a duplicate of a spreadsheet and I expect to have a copy of the sheets while keeping the original ones.

### What is the current behavior?

Copy methods removes the original sheets from the source spreadsheet. The problem is that the `Worksheet@rebindParent` method that calls `Spreadsheet@removeSheetByIndex`. I understand this method is useful when moving a sheet from one spreadsheet to another, but does not work for copies.

### What are the steps to reproduce?

This is a simple code to reproduce

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// The source has 1 sheet
error_log("#sheets: " . $spreadsheet->getSheetCount()); 

// Let's do the copy
$copy = $spreadsheet->copy();

// Copy is fine
error_log("#sheets in copy: " . $copy->getSheetCount());

// Source spreadsheet has no sheets !!!!!
error_log("#sheets: " . $spreadsheet->getSheetCount());
```

### Which versions of PhpSpreadsheet and PHP are affected?

At least 1.8 and 1.12

I as using 1.8 in my project and upgraded to the last 1.12 and I found the problem in both of them.

### PR DESCRIPTION
**Pull request by Vagir-dev**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [x] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

Creating a duplicate spreadsheet using the copy() method has the wrong behavior: it moves all the sheets from the source spreadsheet to the target one, rather than just copying them.

Resolves #1483

### CODE REVIEW

**Comment by Vagir-dev** [comment]
@PowerKiKi hi!
Can you help please?

Travis CI shows error:

> There was 1 error:
> 1) PhpOffice\PhpSpreadsheetTests\SpreadsheetTest::testCopySpreadsheet
> **Exception: Serialization of 'SimpleXMLElement' is not allowed**
> /home/travis/build/PHPOffice/PhpSpreadsheet/src/PhpSpreadsheet/Spreadsheet.php:979
> /home/travis/build/PHPOffice/PhpSpreadsheet/src/PhpSpreadsheet/Spreadsheet.php:961
> /home/travis/build/PHPOffice/PhpSpreadsheet/tests/PhpSpreadsheetTests/**SpreadsheetTest.php:69**

I can't figure out the reason for this problem, but here's what I found out:

1) This error does not occur if you run `SpreadsheetTest::testCopySpreadsheet` **as a single test** instead of running all Php spreadsheet tests.
2) This error does not occur if two tests are excluded from all tests:
- tests/PhpSpreadsheetTests/IOFactoryTest.php
- tests/PhpSpreadsheetTests/Reader/XmlTest.php
3) This error does not occur if you comment lines with the **load ()** method in these two tests.
4) This error concerns only loading **Xml** or **Gnumeric** file types.
5) Error raises in this line (PhpSpreadsheet/src/PhpSpreadsheet/Spreadsheet.php:979):
$this->{$key} = unserialize(**serialize($val)**);

Maybe you know what happens during loading **Xml** or **Gnumeric** files, that after then serializing of objects stops working?
I'm confused... :-(

**Comment by oleibman** [comment]
I have an open pull request #1517 to improve Gnumeric coverage. When I use Reader/BaseReader and Reader/Gnumeric from that request, the problem with Gnumeric seems to disappear. Can you confirm whether that also works for you. I wish I could point you to exactly what part of that change (accidentally) made this work, but I'll need to study it some more.
This still leaves the XML Reader as a problem. Improving coverage for it is on my to-do list, and I will keep this problem in mind while working on it.

**Comment by Vagir-dev** [comment]
> When I use Reader/BaseReader and Reader/Gnumeric from that request, the problem with Gnumeric seems to disappear.

@oleibman, hi!
Yes, you are right-indeed, the problem with **Gnumeric** has disappeared! Thank you!!
Now I will wait for your PR, which will fix the **XML Reader**. :)
Please let me know when it's ready, because until then **my PR can't pass Travis CI**. :(

**Comment by MarkBaker** [comment]
@oleibman's PR has now been merged to master

**Comment by Vagir-dev** [comment]
> @oleibman's PR has now been merged to master

Thanks!

@MarkBaker, may I switch the status of my PR from "Draft" to "Open"?
Could you then merge it to master?
Coz it's not my failt that the test in this PR cannot pass Travis CI. My code has nothing to do with this.

**Comment by oleibman** [comment]
My changes for XML won't be ready for at least a few days, and, alas, not as lucky as those for Gnumeric, and do not appear to correct whatever this problem is. I am still investigating. However, I believe you can get a successful test by annotating it with @runInSeparateProcess.

**Comment by Vagir-dev** [comment]
> However, I believe you can get a successful test by annotating it with @runInSeparateProcess.

It worked, thank you!

**Comment by Vagir-dev** [comment]
Please don't merge this PR for now - it needs addition checking!

**Comment by MarkBaker** [comment]
Ok vagir, I'll hold off merging for the moment until you let me know that you're ready

A useful convention that gitlab provides is prefixing the PR name with `WIP:`, and that text prefix prevents merging until it is removed; and it makes it immediately visible in the MR list. github doesn't work the same way, but I've prefixed my current PR in the same way so that it's obvious in the list

**Comment by PowerKiKi** [comment]
I changed this PR to draft status. So you can let us know whenever it is ready to be reviewed by changing its status again.

**Comment by Vagir-dev** [comment]
@MarkBaker, @PowerKiKi, thank you for your help!

**Comment by yaotzin1** [comment]
ok then. maybe you will provide any workaround for above issue?

**Comment by oleibman** [comment]
Addressed by PR #2951 in July 2022.

**Pull request closed without merging**
