### PR TITLE
Allow ANCHORARRAY as Valid DataValidation List

### LINKED ISSUE #4197: ANCHORARRAY() doen't work in validation
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The correct rendered of ANCHORARRAY() in validatios

### What is the current behavior?
When use ANCHORARRAY() in validations, doesn't rendered

$validation->setFormula1('=ANCHORARRAY($B$1)');

imagen

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$sheet = $spreadsheet->getActiveSheet();

$validation = $sheet->getCell("A1")->getDataValidation();

$validation->setType(DataValidation::TYPE_LIST);
$validation->setErrorStyle(DataValidation::STYLE_STOP);
$validation->setAllowBlank(true);
$validation->setShowDropDown(true);
$validation->setFormula1('=ANCHORARRAY($B$1)');

$sheet->getCell("A1")->setDataValidation($validation);

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [x ] Data Validations
- [x ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### PR DESCRIPTION
**Pull request by oleibman**
Fix #4197. Overlooked in the introduction of Dynamic Arrays, Data Validation can specify a list to be a result of the spill operator, which is implemented via the ANCHORARRAY function.

It appears that function `DataValidator::isValid` will not work if the list is specified in this manner, nor if it is specified as a defined name. Fixing those situations will be difficult (defined names probably easier than ANCHORARRAY), and there is no reason to delay this change waiting for those to be fixed. I will open a new issue when this PR is merged.

This is:

- [x] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests

Checklist:

- [x] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [x] New unit tests have been added
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change and a link to the pull request if applicable
- [ ] Documentation is updated as necessary

### Why this change is needed?

Provide an explanation of why this change is needed, with links to any Issues (if appropriate).
If this is a bugfix or a new feature, and there are no existing Issues, then please also create an issue that will make it easier to track progress with this PR.

### CODE REVIEW

**Comment by siarheipashkevich** [comment]
@oleibman it is does not work with russia words

image

```
local.ERROR: preg_match(): failed executing "/^[^\*\:\/\\\?\[\]\+\-\% \'\^\&\<\>\=\,\;\#\(\)\"\{\}]+(\:[^\*\:\/\\\?\[\]\+\-\% \'\^\&\<\>\=\,\;\#\(\)\"\{\}]+)?\!\$?[A-Ia-i]?[A-Za-z]\$?\d+$/u": Malformed UTF-8 characters, possibly incorrectly encoded {"exception":"[object] (Composer\\Pcre\\PcreException(code: 4): preg_match(): failed executing \"/^[^\\*\\:\\/\\\\\\?\\[\\]\\+\\-\\% \\'\\^\\&\\<\\>\\=\\,\\;\\#\\(\\)\\\"\\{\\}]+(\\:[^\\*\\:\\/\\\\\\?\\[\\]\\+\\-\\% \\'\\^\\&\\<\\>\\=\\,\\;\\#\\(\\)\\\"\\{\\}]+)?\\!\\$?[A-Ia-i]?[A-Za-z]\\$?\\d+$/u\": Malformed UTF-8 characters, possibly incorrectly encoded at /Users/sergey/Herd/esupl-api/vendor/composer/pcre/src/PcreException.php:29)
[stacktrace]
#0 /Users/sergey/Herd/esupl-api/vendor/composer/pcre/src/Preg.php(37): Composer\\Pcre\\PcreException::fromFunction('preg_match', '/^[^\\\\*\\\\:\\\\/\\\\\\\\\\\\?\\\\...')
#1 /Users/sergey/Herd/esupl-api/vendor/composer/pcre/src/Preg.php(303): Composer\\Pcre\\Preg::match('/^[^\\\\*\\\\:\\\\/\\\\\\\\\\\\?\\\\...', '\"\\xD1', Array, 0, 0)
#2 /Users/sergey/Herd/esupl-api/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xls/Parser.php(1097): Composer\\Pcre\\Preg::isMatch('/^[^\\\\*\\\\:\\\\/\\\\\\\\\\\\?\\\\...', '\"\\xD1')
```

**Comment by oleibman** [comment]
@siarheipashkevich I am unable to duplicate your error. Perhaps it comes farther along in the code than what you have identified. At any rate, here's the code I used (I changed cell B0 to B1 - I'm a bit surprised that your references to B0 did not cause an exception):
```php
    public static function issue(): void
    {
        $spreadsheet = new Spreadsheet();
        $worksheet = $spreadsheet->getActiveSheet();

        $validation = $worksheet->getCell('B1')->getDataValidation();
        $validation->setType(DataValidation::TYPE_LIST);
        $validation->setErrorStyle(DataValidation::STYLE_STOP);
        $validation->setAllowBlank(false);
        $validation->setShowInputMessage(true);
        $validation->setShowErrorMessage(true);
        $validation->setShowDropDown(true);
        $validation->setFormula1('"слово, слово"'); // << russia words here
        $dataValidator = new DataValidator();
        $worksheet->getCell('B1')->setValue('слово');
        // expect true
        var_dump($dataValidator->isValid($worksheet->getCell('B1')));
        $worksheet->getCell('B1')->setValue('слов');
        // expect false
        var_dump($dataValidator->isValid($worksheet->getCell('B1')));

        $worksheet->setDataValidation('B2:B1500', clone $validation);
        echo "Done\n";
    }
```
And here are my results, exactly as expected:
```
C:\git\issue.4266.php:28:
bool(true)
C:\git\issue.4266.php:31:
bool(false)
Done
```

**Comment by siarheipashkevich** [comment]
@oleibman thanks for your response. Do you use `1.29.9` version?

**Comment by oleibman** [comment]
@siarheipashkevich I just tried with 1.29.9 and received the same expected results without any exceptions.

**Comment by siarheipashkevich** [comment]
@oleibman it's very strange. Could you please check this issue https://github.com/SpartnerNL/Laravel-Excel/issues/4266 where I attached more code?

**Comment by oleibman** [comment]
Aha, the error does show up later than you reported. It happens when I try to save the spreadsheet as Xls. And, yes, it does not happen with Latin characters. I will research. In the meantime, you can save the spreadsheet as Xlsx instead without problems.

**Comment by siarheipashkevich** [comment]
@oleibman thanks, I'll wait your solution.

**Comment by oleibman** [comment]
@siarheipashkevich If you can test against the parseutf8 branch (or, guessing from our conversation, the release1291 branch), please do so.

**Comment by siarheipashkevich** [comment]
@oleibman unfortunately I can't, because I use laravel-excel package. Only if you create a new patch release in that case I'll possible to check.

**Comment by oleibman** [comment]
New releases are now available.

**Comment by siarheipashkevich** [comment]
@oleibman it's working right now, thank you so much 🚀

**Pull request merged**
