### PR TITLE
More Bubble Chart Fixes

### PR DESCRIPTION
**Pull request by oleibman**
Continuing the work from #2828, #2841, #2846, and #2852. This is probably my last change in this area for a while.

Bubble charts can have bubbles of different sizes. Phpspreadsheet had not supported this. Openpyxl comes with sample code to generate such a chart. I was especially drawn to that solution because its namespace usage would have been unexpected before 2852. And it turned out to come with other surprises - use of absolute paths in the .rels files (PhpSpreadsheet expected only relative), use of a one-cell anchor to place the chart (PhpSpreadsheet expected two-cell anchor or absolute positioning), plaintext in the legend (Phpspreadsheet expected RichText), no cached values for chart data. Excel handles the file okay, and this PR makes sure PhpSpreadsheet does as well. This file is now Samples/Templates/32readwriteBubbleChart2, and is used for both generating a sample output file and in formal tests. A new sample in the 33* series demonstrates how to code these.

This is:

```
- [x] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests
```

Checklist:

- [ ] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [x] New unit tests have been added
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

Provide an explanation of why this change is needed, with links to any Issues (if appropriate).
If this is a bugfix or a new feature, and there are no existing Issues, then please also create an issue that will make it easier to track progress with this PR.

### CODE REVIEW

**Comment by fredpe** [comment]
Leaving a note here while I am also preparing a new issue for a bug with a change made in this PR. We noticed this issue when upgrading to version 1.24.0 which included this PR here, and the problem is still present in the newest version 1.26.0. Running on 1.23.0, it is not showing this issue.

The error we are receiving after this PR, and which was not present before this PR with same inputs, is:
```
[Fri Dec 23 11:01:56.494355 2022] [php:notice] [pid 17] [client 172.16.0.243:21160] ErrorException: Warning: Undefined array key 0 in /quintly/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Chart.php:1398
Stack trace:
#0 /quintly/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Chart.php(1260): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx\\Chart->writePlotSeriesValues(Object(PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues), Object(PhpOffice\\PhpSpreadsheet\\Shared\\XMLWriter), 'barChart', 'str')
#1 /quintly/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Chart.php(273): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx\\Chart->writePlotGroup(Object(PhpOffice\\PhpSpreadsheet\\Chart\\DataSeries), 'barChart', Object(PhpOffice\\PhpSpreadsheet\\Shared\\XMLWriter), false, false, 'percentStacked')
#2 /quintly/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Chart.php(94): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx\\Chart->writePlotArea(Object(PhpOffice\\PhpSpreadsheet\\Shared\\XMLWriter), Object(PhpOffice\\PhpSpreadsheet\\Chart\\PlotArea), NULL, NULL, Object(PhpOffice\\PhpSpreadsheet\\Chart\\Axis), Object(PhpOffice\\PhpSpreadsheet\\Chart\\Axis))
#3 /quintly/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(399): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx\\Chart->writeChart(Object(PhpOffice\\PhpSpreadsheet\\Chart\\Chart), false)
#4 /quintly/src/Metrics/Export/Office/Excel.php(277): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx->save('/tmp/reportsp16...')
#5 /quintly/src/Metrics/Export/Office/Excel.php(79): Metrics\\Export\\Office\\Excel->writeSheet()
#6 /quintly/src/Tool/View/Data/ExcelMetricsView.php(75): Metrics\\Export\\Office\\Excel->createReport(Array, 'MM/DD/YYYY')
#7 /quintly/src/Application/Tool/DataResponseRenderingService.php(64): Tool\\View\\Data\\ExcelMetricsView->render('B04 & FCB Repor...', Array, Object(Metrics\\UserSettings))
#8 /quintly/src/Tool/Controller/DataController.php(176): Application\\Tool\\DataResponseRenderingService->getResponseByFormat('xlsx', Object(Metrics\\ExportContext), Array, Object(Metrics\\UserSettings), Object(Domain\\Customer\\Entity\\User), Object(DoctrineProxies\\__CG__\\Domain\\Customer\\Entity\\Space))
#9 /quintly/src/Common/Foundation/AbstractController.php(64): Tool\\Controller\\DataController->loadDashboardMetricsAction()
#10 /quintly/projects/tool/public/index-zend.php(53): Common\\Foundation\\AbstractController->callAction('loadDashboardMe...')
#11 {main}, referer: [...]
```

It is related to the change in this PR to this line:
https://github.com/PHPOffice/PhpSpreadsheet/pull/2856/files#diff-97c03ccbe2f3cac6b5390cd2c45c1a12d6786c13851ea9cbe74416cc2db8b066R1445

`if ($count > 1 || ($count === 1 && "=$source" !== (string) $values[0])) {`

The issue is caused because the point count (`$plotSeriesValues->getPointCount()`) is out of sync with the number of data values (`$plotSeriesValues->getDataValues()`). Our log output shows that the point count is 1, while the data values is an empty array. As a result, the mentioned exception is thrown. Here is a print_r of the PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues object when the issue occurs:

```
PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues Object
(
    [objectState:protected] => 
    [glowSize:protected] => 
    [glowColor:protected] => PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor Object
        (
            [value:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [type:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [alpha:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [brightness:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
        )

    [softEdges:protected] => Array
        (
            [size] => 
        )

    [shadowProperties:protected] => Array
        (
            [presets] => 
            [effect] => 
            [size] => Array
                (
                    [sx] => 
                    [sy] => 
                    [kx] => 
                    [ky] => 
                )

            [blur] => 
            [direction] => 
            [distance] => 
            [algn] => 
            [rotWithShape] => 
        )

    [shadowColor:protected] => PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor Object
        (
            [value:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => black
            [type:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => prstClr
            [alpha:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 40
            [brightness:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
        )

    [lineColor:protected] => PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor Object
        (
            [value:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [type:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [alpha:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [brightness:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
        )

    [lineStyleProperties:protected] => Array
        (
            [width] => 
            [compound] => 
            [dash] => 
            [cap] => 
            [join] => 
            [arrow] => Array

   (
                    [head] => Array
                        (
                            [type] => 
                            [size] => 
                            [w] => 
                            [len] => 
                        )

                    [end] => Array
                        (
                            [type] => 

            [size] => 
                            [w] => 
                            [len] => 
                        )

                )

        )

    [dataType:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => String
    [dataSource:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 'Instagram Interactions Distribu'!$A$4:$A$4
    [formatCode:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 
    [pointMarker:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 
    [markerFillColor:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor Object
        (
            [value:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [type:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [alpha:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [brightness:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
        )

    [markerBorderColor:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor Object
        (
            [value:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [type:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [alpha:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
            [brightness:PhpOffice\\PhpSpreadsheet\\Chart\\ChartColor:private] => 
        )

    [pointSize:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 3
    [pointCount:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 1
    [dataValues:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => Array
        (
        )

    [fillColor:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 
    [scatterLines:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 1
    [bubble3D:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 
    [labelLayout:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 
    [trendLines:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => Array
        (
        )

    [smoothLine:PhpOffice\\PhpSpreadsheet\\Chart\\DataSeriesValues:private] => 
)
```

Again, I am sorry I am not handing in an isolated test case yet, which I am happy to provide in a separate bug issue, but it will require some more preparation. I still thought probably someone more into these objects immediately sees why this "out of sync" is happening, or if it's even valid and the check should rather be on `count($values) === 1` instead of `$count === 1` before the array access with `[0]` is happening.

**Comment by oleibman** [comment]
Thank you for the excellent documentation. As you mentioned, please open a new issue. If possible, there is something I would like you to try. The statement which you have identified is:
```php
if ($count > 1 || ($count === 1 && "=$source" !== (string) $values[0])) {
```
If you change that to:
```php
if ($count > 1 || ($count === 1 && array_key_exists(0, $values) && "=$source" !== (string) $values[0])) {
```
I think that will eliminate the error, but it may just push the error along to somewhere further in the program, or it may result in a corrupt or incorrect spreadsheet. I cannot run this test on my own since I do not yet have an example of a failing worksheet. Can you test this and see what happens.

**Comment by fredpe** [comment]
Thank you @oleibman for the very prompt feedback! I have tested the patch you described, and it indeed resolves the error, but the output is not the same anymore, even though the difference is little.

In the following screenshot you see the exact same code with exact same inputs running on 1.23.0 on the left, and 1.26.0 with the array_key_exists patch on the right. As you can see, the charts have the same cells as an input, but render slightly different.

image

Now I am not sure, if this difference in rendering is simply a change that came with other updates since 1.23.0, as also the logic producing the error was just introduced in 1.24.0 and did not exist before. At least I can say, other than formatting differences in the charts, the data inputs and also the construction of the chart itself with its parameters is still correct.

Hope this helps! I will work on the isolated test case in the meanwhile.

**Comment by oleibman** [comment]
Glad that we're on the right track even if we don't have a complete solution yet. I don't think I can do much more without a sample input file and/or program in hand.

**Pull request merged**
