### PR TITLE
Additional options for mergeCells() method

### PR DESCRIPTION
**Pull request by MarkBaker**
This is:

```
- [ ] a bugfix
- [X] a new feature
- [ ] refactoring
- [ ] additional unit tests
```

Checklist:

- [X] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [X] New unit tests have been added
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [X] CHANGELOG.md contains a short summary of the change
- [X] Documentation is updated as necessary

### Why this change is needed?

Handle additional merge options like those provided in OpenOffice or LibreOffice to hide cell values in a merge range rather than empty them, or to merge the values as well as the cells

This includes reading hidden values in merge ranges, so that Unmerging can restore their visibility

See [Issue #3065](https://github.com/PHPOffice/PhpSpreadsheet/issues/3065)

### CODE REVIEW

**Comment by naotake51** [comment]
@MarkBaker 

With this PR, the following code now gives an error:
Is that what you intended?

```php
$spreadsheet = new Spreadsheet();
$worksheet = new Worksheet($spreadsheet, 'Sheet1');
$worksheet->mergeCells('A1:A2'); // PhpOffice\PhpSpreadsheet\Exception: Sheet does not exist.
```

If you run addSheet before mergeCells, you won't get an error.

```php
$spreadsheet = new Spreadsheet();
$worksheet = new Worksheet($spreadsheet, 'Sheet1');
$spreadsheet->addSheet($worksheet);
$worksheet->mergeCells('A1:A2'); // OK
```

Stack Trace
```
/Users/takeshitanaoki/work/project/tmp/PhpSpreadsheet/src/PhpSpreadsheet/Spreadsheet.php:753
/Users/takeshitanaoki/work/project/tmp/PhpSpreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php:1483
/Users/takeshitanaoki/work/project/tmp/PhpSpreadsheet/src/PhpSpreadsheet/Cell/Cell.php:536
/Users/takeshitanaoki/work/project/tmp/PhpSpreadsheet/src/PhpSpreadsheet/Cell/Cell.php:174
/Users/takeshitanaoki/work/project/tmp/PhpSpreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php:1819
/Users/takeshitanaoki/work/project/tmp/PhpSpreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php:1808
```

**Comment by MarkBaker** [comment]
Hmmm, yes! A worksheet that hasn't yet been added to the Spreadsheet will throw errors now, because merging cells needs to be able to read the cell formatting to get the value, and that's maintained as a style. There will be similar issues if you tried to set a cell style before the worksheet is added to the Spreadsheet, because all style definitions is maintained at the Spreadsheet level.

I need to ensure that creating a new Worksheet when you specify a Spreadsheet cleanly attaches that worksheet to the Spreadsheet, without the need to do an explicit call to `addSheet()`, but that calling `addSheet()` shouldn't break when the worksheet is already attached to that Spreadsheet.

**Comment by MarkBaker** [comment]
Unfortunately, something that should seem so easy causes havok when running the test suite:
```
ERRORS!
Tests: 13082, Assertions: 16180, Errors: 835, Failures: 15, Skipped: 1, Incomplete: 4, Risky: 2.
```

So it's going to need a bit more work.

**Comment by naotake51** [comment]
Thanks for your reply.
I understand.

**Pull request merged**
