### PR TITLE
Fixed Security Vulnerability: Insecure Randomness (CWE ID 330)

### PR DESCRIPTION
**Pull request by wr3nch0x1**
Fixed Security Vulnerability: Insecure Randomness (CWE ID 330)

This is:

```
- [Yes] a bugfix
- [No] a new feature
```

Checklist:

- [Yes] Changes are covered by unit tests
- [Yes] Code style is respected
- [Yes] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

To prevent attacks to predict the randomness of values.

### CODE REVIEW

**Comment by MarkBaker** [comment]
> The software may use insufficiently random numbers or values in a security context that depends on unpredictable numbers.

Is this really `a security context that depends on unpredictable numbers` that you need to highlight it as a `Security Vulnerability`? If so, then you should really have applied responsible disclosure.

**Comment by wr3nch0x1** [comment]
Hi @MarkBaker, I am not able to find any responsible disclosure guideline in security tab. Can you please help me in that?

Also, Huntr.dev is a security bug bounty program which helps us to get the bounty of disclosures. That's why thought to disclosed on https://huntr.dev/bounties/1624994698993-PHPOffice/PhpSpreadsheet/

Thanks :)

**Comment by MarkBaker** [comment]
Generally speaking, I would expect appropriate disclosure to ___NOT___ involve posting a PR with a big message saying "Security Vulnerability".

Also, if you look at the context of the change, is this really `a security context that depends on unpredictable numbers`? The randomness here is being used to generate unique IDs, not in a security context, but to avoid a clash.

If this really was a security vulnerability, then I would be very concerned about that method of highly public disclosure. In the past when we have had responsible disclosure, it has been a direct and secure approach by the security company in question, and I would expect Huntr.dev has such an appropriate process.

**Comment by wr3nch0x1** [comment]
Yes, huntr do have a secure approach. Only reporter and program owner can
see the report of the vulnerability until you merge the fix.

If this is not security related IDs then you can ignore them.

**Comment by MarkBaker** [comment]
Not a security issue

**Comment by zidingz** [comment]
Hi Mark,

Would it be possible to kindly add a `SECURITY.md` file with an e-mail to your repository? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this as the best way to ensure security issues are responsibly disclosed, and it would massively help security researchers get in touch responsibly next time. Thanks!

**Pull request closed without merging**
