### PR TITLE
[WIP] - Add Support for twoCellAnchor Object Positioning for Drawing 

### PR DESCRIPTION
**Pull request by sgarwood**
Addition of support for twoCellAnchors in PHPSpreadsheet

This is:

```
- [ ] a bugfix
- [x] a new feature
```

Checklist:

- [ ] Changes are covered by unit tests
- [ ] Code style is respected
- [ ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

Please see issue #1159

### CODE REVIEW

**Comment by sgarwood** [comment]
TODO:

- [ ] Finish test
- [ ] Finish reader
- [ ] Polish API
- [ ] Add class constants instead of Magic Strings

**Comment by sgarwood** [comment]
Please could I have some help with my test, I am unsure why it is failing 

It would appear 
```php
  if ($xfrm) 
```
Is evaluating to truthy when it shouldn't be but I am unsure how my changes have broken this test.

```
PhpOffice\PhpSpreadsheet\Reader\Xlsx::getArrayItem(): Node no longer exists

/app/src/PhpSpreadsheet/Reader/Xlsx.php:1851
```

**Comment by sgarwood** [comment]
Please, could I have some feedback on this?

**Comment by PowerKiKi** [comment]
It's unclear to me too. That definitely looks similar to https://stackoverflow.com/questions/2502038/simplexml-node-no-longer-exists, but I can really figure out what is going on in our case...

**Comment by oleibman** [comment]
Equivalent change was implemented with PR #2632 and PR #2674 in Feb/Mar 2022.

**Pull request closed without merging**
