### PR TITLE
make voku/anti-xss an optional package

### PR DESCRIPTION
**Pull request by jasverix**
This package installs voku/portable-utf8 which "sanitizes" REQUEST_URI in globals, which in turn crashed our entire system. 

Library packages should never 'do' anything, just be libraries.

This is:

```
- [ x ] a bugfix
- [ ] a new feature
```

Checklist:

- [ ] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?
Our system did break down some time ago after installing voku/portable-utf8 because it sanitizes global variable REQUEST_URI. After that, the package is completely banned from our code base. I don't know if you will accept making it optional (only used one place..), but I will give it a try.

### CODE REVIEW

**Comment by jasverix** [comment]
Yes, I understand, and I just wanted to open discussion, because I did not think you would just remove it. But voku/portable-utf8 has a bootstrap.php file which does a little more than we can accept - libraries should in my world just add classes and not do things on each request.

I would not have any problems using htmlpurifier, that library is not adding any bootstrap file at least (and has much less dependencies). I can fix the PR to do that instead, and then you can consider. I am not using the HTML Writer myself.

**Comment by jasverix** [comment]
Tried to implement this now, but you have unit-tests requiring that this string is not allowed:
```<div class="comment">javascript:alert(1)</div>```

That's not dangerous HTML, it's just strange plain text. As an attribute, though, it is more dangerous. But should we still not allow this text? Looks like anti-xss removed it completely, but HTMLPurifier leaves it (but the first test `<script>alert('test')</script>` is passing)

**Comment by MarkBaker** [comment]
I've updated the tests, and modified the code to use HTMLPurifier instead of anti-xss in a [separate PR](https://github.com/PHPOffice/PhpSpreadsheet/pull/1751)

**Comment by jasverix** [comment]
Great! Thank you!

**Pull request closed without merging**
