### PR TITLE
Add null typehint to Worksheet::getColumnDimension() since it returns null

### PR DESCRIPTION
**Pull request by simPod**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Should this be somehow more documented? It has always returned null.

Checklist:

- [ ] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### CODE REVIEW

**Comment by simPod** [comment]
CI says there's some violation but does not say what is the violation.

**Comment by oleibman** [comment]
To get rid of the CI violation, try `@return null|ColumnDimension` rather than `@return ColumnDimension|null` in your Doc block.

**Comment by simPod** [comment]
oh it's the other way it usually is. thx

**Comment by MarkBaker** [comment]
In most cases, when a phpdoc annotation indicates that a method accepts or returns multiple different datatypes, they should be listed alphabetically (e.g. `float|int` rather than `int|float`); but `null` is a special case, in the same way that we typehint `?MyObjectClass`, with the `?` in front of the object class name

**Review by MarkBaker — CHANGES_REQUESTED** [review]
The same issue applies to `getRowDimension()` and to `getColumnDimensionByColumn()` as well: could you include fixing those docblocks in the same PR?

Thanks

**Comment by simPod** [comment]
Yes. Done in the next commit.

Btw what will the special case be with PHP8 union types for eg. `fcn(): MyObjectClass|null`?

**Comment by MarkBaker** [comment]
> Btw what will the special case be with PHP8 union types for eg. fcn(): MyObjectClass|null?

I'm not sure that any standards for using the keyword `null` in a union return-type have been defined yet; my inclination would be to use `?MyObjectClass` as at present; and apply union types only when you have something like `fcn(): false|MyObjectClass`; and with scalars before objects.

We try to adhere to PSR-12 for PHPSpreadsheet, so really it's a case of waiting for the FIG to identify appropriate standards; but until we have PHP8 as a minimum version, it's not an option for us (and that's a few years away yet)

**Comment by simPod** [comment]
just curious, thanks for input!

**Review by MarkBaker — APPROVED** [review]
Thanks for the contribution, and for the quick response for my request to fix the other methods as well.

**Pull request merged**
