### PR TITLE
Fix for #2224

### LINKED ISSUE #2224: Data Validation flags not read correctly when reading XLSX files
This is:

```
- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Data validation flags like allowBlank, showDropDown, showInputMessage, and showErrorMessage flags are set correctly when reading in a XLSX

### What is the current behavior?
Values are always set to false (except showDropDown which inverts the logic incorrectly and is always true)

### What are the steps to reproduce?
Read in the XLSX file with data validations set with an input or error message, write file back out to a new XLSX file. Messages will be unset.

The code in PhpOffice\PhpSpreadsheet\Reader\Xlsx\DataValidations looks suspect. In load() the value for $dataValidation record is:

```php
SimpleXMLElement Object
(
    [@attributes] => Array
        (
            [allowBlank] => true
            [operator] => between
            [prompt] => Enter a valid date
            [showDropDown] => true
            [showErrorMessage] => true
            [showInputMessage] => true
            [sqref] => C505:C1003
            [type] => custom
        )

    [formula1] => OR(NOT(ISERROR(DATEVALUE(C504))), AND(ISNUMBER(C504), LEFT(CELL("format", C504))="D"))
    [formula2] => 0
)
```

however the resulting PhpOffice\PhpSpreadsheet\Cell\DataValidation Object becomes

```php
PhpOffice\PhpSpreadsheet\Cell\DataValidation Object
(
    [formula1:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => OR(NOT(ISERROR(DATEVALUE(C504))), AND(ISNUMBER(C504), LEFT(CELL("format", C504))="D"))
    [formula2:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => 0
    [type:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => custom
    [errorStyle:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => 
    [operator:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => between
    [allowBlank:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => 
    [showDropDown:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => 1
    [showInputMessage:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => 
    [showErrorMessage:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => 
    [errorTitle:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => 
    [error:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => 
    [promptTitle:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => 
    [prompt:PhpOffice\PhpSpreadsheet\Cell\DataValidation:private] => Enter a valid date
)
```

$dataValidation is a SimpleXML object

```php
 object(SimpleXMLElement)#15136 (1) {
  [0]=>
  string(4) "true"
}
```

therefore the loose comparison in PhpOffice\PhpSpreadsheet\Reader\Xlsx\DataValidations::load() will always be false

```php
$docValidation->setAllowBlank($dataValidation['allowBlank'] != 0);
```

This is the same for other flags like showDropDown, showInputMessage, showErrorMessage

Additionally the logic for showDropDown is inverted (and then inverted again in the Xlsx writer)

### Which versions of PhpSpreadsheet and PHP are affected?
Current release and master branch

### PR DESCRIPTION
**Pull request by lucasnetau**
Fixes #2224 Fix reading data validation flags allowBlank, showDropDown, showInputMessage, showErrorMessage in XLSX reader (was a loose comparison of SimpleXML object to integer), flag values may also be string true/false not just 0/1.

  filter_var( $flag, FILTER_VALIDATE_BOOLEAN) chosen to handle both 0/1 and true/false values in the file being read.

This is:

```
- [X] a bugfix
- [ ] a new feature
```

Checklist:

- [X] Changes are covered by unit tests
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [X] CHANGELOG.md contains a short summary of the change
- [-] Documentation is updated as necessary

### Why this change is needed?
Data validation flags are lost when reading an XLSX file containing true/false boolean values and writing it out after editing.

### CODE REVIEW

**Comment by oleibman** [comment]
Are you able to add some unit tests to show that files which do have true/false rather than 1/0 are handled correctly?

**Comment by lucasnetau** [comment]
OK, I shall attempt a unit test for this PR.

The true/false values are in xlsx documents created or edited in LibreOffice. This is valid under the schema definition https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.datavalidation?view=openxml-2.8.1 

> The possible values for this attribute are defined by the W3C XML Schema boolean datatype.

And based on https://www.w3.org/TR/xmlschema-2/#boolean

> An instance of a datatype that is defined as ·boolean· can have the following legal literals {true, false, 1, 0}.

**Comment by lucasnetau** [comment]
Unit tests added with both DataValidation defined with true/false and also 1/0

I've reverted the change to showDropDown as upon further investigation this flag is misdefined in the specification and acts as a hideDropDown, which is the reason behind the inversion in both Reader and Writer. I have instead added a brief comment on the relevant lines when it is read and written.

**Comment by oleibman** [comment]
Thank you for your contribution, and for the excellent documentation of what you've done.

**Pull request merged**
