### PR TITLE
Limited Support for Form Controls V2 (ListBox, Buttons, etc.)

### LINKED ISSUE #1770: Support for LegacyDrawing
This is:

```
- [ ] a bug report
- [x ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
I'm using Excel 2019, php 7.4, and the master branch of PhpSpreadsheet

It seems as though the Xlsx Reader does not read the legacyDrawing element. If you read in an xlsm that contains a FormControl button and then save the spreadsheet, the button will be missing when you open the newly saved file. If you unzip the newly saved file, add back the missing legacyDrawing element, and re-zip then the button will be available.

### What is the expected behavior?
The saved xlsm retains the button

### What is the current behavior?
The saved xlsm no longer has the button

### What are the steps to reproduce?
1. Open Excel 2019
2. Create a blank workbook
3. Add a button -> click the Developer tab, then Insert, then select the box icon under Form Controls
4. In the AssignMacro window, record a new marco. Use the default values. The recorded macro can be whatever you want. I just clicked a random cell and gave it a fixed value (e.g. the character 'a').
5. Save the file anywhere you want and call it 'test.xlsm'.
6. Run the code below:
```php
<?php

require __DIR__ . '/vendor/autoload.php';
$reader = new XlsxReader();
$sheet = $reader->load('path/to/test.xlsm');
$writer = new XlsxWriter($sheet);
$writer->save('path/to/test_2.xlsm');
```
7. Open 'test_resaved.xlsm' and you'll find there is no button.

Optional

8. Unpack both `test.xlsm` and `test_resaved.xlsm` using your favorite unzip program (I used WinRAR)
9. Open and compare `path/to/test/xl/worksheet/sheet1.xml` and `path/to/test_resaved/xl/worksheet/sheet1.xml`
10. Somewhere in the file you'll find an element called `<drawing>` and they will be the same in both files
11. In the test version of `sheet1.xml` you'll also find a `<legacyDrawing>` element. That element will be missing from the test_resaved version.
12. Copy-paste the legacy drawing element
13. Recreate `test_resaved.xlsm` by zipping everything up again (I used WinRAR, fastest)
14. Open `test_resaved.xlsm` and you see the button.

### LINKED ISSUE #2388: Macro Buttons and List boxes are removed
This is: I have an XLSM with buttons and list box (macros) when I am opening an XLSM file and updating a cell value with text and saving it as different file.

$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($filePath);
$spreadsheet->getCalculationEngine()->suppressFormulaErrors=true;
.
.
.
$writer = new Xlsx($spreadsheet);
$writer->save('output.xlsm');

In the new file buttons and list boxes are missing.

### What is the expected behavior?
Button and List box should be present in the new file because we are saving the existing file with different name.

### What is the current behavior?
Button and list box are removed.

### Which versions of PhpSpreadsheet and PHP are affected?
1.19

### LINKED ISSUE #2396: Image missing
This is: In one one of the scenario I observed the image is missing from a sheet. I have mentioned the steps to reproduce below.

### What is the expected behavior?
Image shouldn't be missing.

### What is the current behavior?
Image is getting removed.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:
Steps:
Create a Xlsx with 7 sheets. Add image to sheets 1,2,4,7.
Add a List Box from Developer tab to sheet 6
Add a button to Sheet 7 along with a image.

After opening and saving the file with different name using PHPSpreadsheet, I see the image is missing from sheet 4. I have attached a sample excel where issue can be easily reproduced.

```php
<?php
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();

// add code that show the issue here...

$spreadsheet = $reader->load($file);

$writer = new Xlsx($spreadsheet);
$writer->save('TextColorOutput.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.19
[ImageIssueInput.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7532647/ImageIssueInput.xlsx)

### LINKED ISSUE #2661: Copying File with Checkboxes Produces Corrupt Result
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
create file or write without errors

### What is the current behavior?
error when opening created file 
Repaired Records: Feature formatting (DXFs) from /xl/styles.xml part (Styles)
image-20220307-093628

[corrupted_file.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8206813/corrupted_file.xlsx)

### What are the steps to reproduce?
load the template file and then write data into it and save as new file and then try to open.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

please see curupted file with the issue

```php
<?php

require __DIR__ . '/

vendor/autoload.php';


// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet a
nd PHP are affected?
1.22.0

#### Template file
[template.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8206781/o2_api_new_request_template.xlsx)

### LINKED ISSUE #2904: Button Disappear When Using Funtion Load in IOFactory
This is: error, when i use function load in IOFactory my button in file xls disappear. Please help me with issue.
[
image
](url)
```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### LINKED ISSUE #3125: simplexml_load_string / Opening and ending tag mismatch in XLSX-Reader
This is:

```
- [ x] a bug report
```

### What is the expected behavior?
no warning

### What is the current behavior?
simplexml_load_string(): Entity: line 59: parser error : Opening and ending tag mismatch: br line 58 and font

### What are the steps to reproduce?
Sorry, can't distribute xlsx-file

```php
   $content=>
<xml xmlns:v="urn:schemas-microsoft-com:vml"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel">
 <o:shapelayout v:ext="edit">
  <o:idmap v:ext="edit" data="3"/>
 </o:shapelayout><v:shapetype id="_x0000_t201" coordsize="21600,21600" o:spt="201"
  path="m,l,21600r21600,l21600,xe">
  <v:stroke joinstyle="miter"/>
  <v:path shadowok="f" o:extrusionok="f" strokeok="f" fillok="f" o:connecttype="rect"/>
  <o:lock v:ext="edit" shapetype="t"/>
 </v:shapetype><v:shape id="_x0000_s3073" type="#_x0000_t201" style='position:absolute;
  margin-left:150.6pt;margin-top:422.4pt;width:195pt;height:0;z-index:1;
  mso-wrap-style:tight' o:button="t" fillcolor="buttonFace [67]" strokecolor="windowText [64]"
  o:insetmode="auto">
  <v:fill color2="buttonFace [67]" o:detectmouseclick="t"/>
  <o:lock v:ext="edit" rotation="t"/>
  <v:textbox style='mso-direction-alt:auto' o:singleclick="f">
   <div style='text-align:center'><font face="Mazda Type" size="200"
   color="#000000">Datenimport aus BI-Tool</font></div>
  </v:textbox>
  <x:ClientData ObjectType="Button">
   <x:Anchor>
    2, 1, 33, 0, 2, 326, 35, 20</x:Anchor>
   <x:PrintObject>False</x:PrintObject>
   <x:AutoFill>False</x:AutoFill>
   <x:FmlaMacro>[0]!Datenübernahme</x:FmlaMacro>
   <x:TextHAlign>Center</x:TextHAlign>
   <x:TextVAlign>Center</x:TextVAlign>
  </x:ClientData>
 </v:shape><v:shape id="_x0000_s3075" type="#_x0000_t201" style='position:absolute;
  margin-left:364.2pt;margin-top:422.4pt;width:175.2pt;height:0;z-index:2;
  mso-wrap-style:tight' o:button="t" fillcolor="buttonFace [67]" strokecolor="windowText [64]"
  o:insetmode="auto">
  <v:fill color2="buttonFace [67]" o:detectmouseclick="t"/>
  <o:lock v:ext="edit" rotation="t"/>
  <v:textbox style='mso-direction-alt:auto' o:singleclick="f">
   <div style='text-align:center'><font face="Calibri" size="220"
   color="#000000">Monatsversion speichern &amp; hochladen</font></div>
  </v:textbox>
  <x:ClientData ObjectType="Button">
   <x:Anchor>
    3, 1, 33, 0, 4, 185, 36, 0</x:Anchor>
   <x:PrintObject>False</x:PrintObject>
   <x:AutoFill>False</x:AutoFill>
   <x:FmlaMacro>[0]!Speichern</x:FmlaMacro>
   <x:TextHAlign>Center</x:TextHAlign>
   <x:TextVAlign>Center</x:TextVAlign>
  </x:ClientData>
 </v:shape><v:shape id="_x0000_s3076" type="#_x0000_t201" style='position:absolute;
  margin-left:545.4pt;margin-top:422.4pt;width:171.6pt;height:0;z-index:3;
  mso-wrap-style:tight' o:button="t" fillcolor="buttonFace [67]" strokecolor="windowText [64]"
  o:insetmode="auto">
  <v:fill color2="buttonFace [67]" o:detectmouseclick="t"/>
  <o:lock v:ext="edit" rotation="t"/>
  <v:textbox style='mso-direction-alt:auto' o:singleclick="f">
   <div style='text-align:center'><font face="Calibri" size="220"
   color="#000000">PDF<span style='mso-spacerun:yes'>  </span>für alle Händler
   exportieren<br>
      </font></div>
  </v:textbox>
  <x:ClientData ObjectType="Button">
   <x:Anchor>
    4, 195, 34, 6, 4, 481, 35, 20</x:Anchor>
   <x:PrintObject>False</x:PrintObject>
   <x:AutoFill>False</x:AutoFill>
   <x:FmlaMacro>[0]!MACS_Generator</x:FmlaMacro>
   <x:TextHAlign>Center</x:TextHAlign>
   <x:TextVAlign>Center</x:TextVAlign>
  </x:ClientData>
 </v:shape><v:shape id="_x0000_s3077" type="#_x0000_t201" style='position:absolute;
  margin-left:546pt;margin-top:422.4pt;width:172.2pt;height:0;z-index:4;
  mso-wrap-style:tight' o:button="t" fillcolor="buttonFace [67]" strokecolor="windowText [64]"
  o:insetmode="auto">
  <v:fill color2="buttonFace [67]" o:detectmouseclick="t"/>
  <o:lock v:ext="edit" rotation="t"/>
  <v:textbox style='mso-direction-alt:auto' o:singleclick="f">
   <div style='text-align:center'><font face="Calibri" size="220"
   color="#000000">PDF für einen Händler exportieren<br>
      </font></div>
  </v:textbox>
  <x:ClientData ObjectType="Button">
   <x:Anchor>
    4, 196, 33, 0, 4, 483, 34, 1</x:Anchor>
   <x:PrintObject>False</x:PrintObject>
   <x:AutoFill>False</x:AutoFill>
   <x:FmlaMacro>[0]!PDF</x:FmlaMacro>
   <x:TextHAlign>Center</x:TextHAlign>
   <x:TextVAlign>Center</x:TextVAlign>
  </x:ClientData>
 </v:shape><v:shapetype id="_x0000_t202" coordsize="21600,21600" o:spt="202"
  path="m,l,21600r21600,l21600,xe">
  <v:stroke joinstyle="miter"/>
  <v:path gradientshapeok="t" o:connecttype="rect"/>
 </v:shapetype><v:shape id="_x0000_s3078" type="#_x0000_t202" style='position:absolute;
  margin-left:1033.8pt;margin-top:453pt;width:105pt;height:69pt;z-index:5;
  visibility:hidden' fillcolor="infoBackground [80]" strokecolor="none [81]"
  o:insetmode="auto">
  <v:fill color2="infoBackground [80]"/>
  <v:shadow color="none [81]" obscured="t"/>
  <v:path o:connecttype="none"/>
  <v:textbox style='mso-direction-alt:auto'>
   <div style='text-align:left'></div>
  </v:textbox>
  <x:ClientData ObjectType="Note">
   <x:MoveWithCells/>
   <x:SizeWithCells/>
   <x:Anchor>
    5, 404, 45, 4, 7, 12, 50, 6</x:Anchor>
   <x:AutoFill>False</x:AutoFill>
   <x:Row>35</x:Row>
   <x:Column>5</x:Column>
   <x:RowHidden/>
  </x:ClientData>
 </v:shape><v:shape id="_x0000_s3079" type="#_x0000_t202" style='position:absolute;
  margin-left:1033.8pt;margin-top:441.6pt;width:108pt;height:67.2pt;z-index:6;
  visibility:hidden' fillcolor="infoBackground [80]" strokecolor="none [81]"
  o:insetmode="auto">
  <v:fill color2="infoBackground [80]"/>
  <v:shadow color="none [81]" obscured="t"/>
  <v:path o:connecttype="none"/>
  <v:textbox style='mso-direction-alt:auto'>
   <div style='text-align:left'></div>
  </v:textbox>
  <x:ClientData ObjectType="Note">
   <x:MoveWithCells/>
   <x:SizeWithCells/>
   <x:Anchor>
    5, 404, 44, 8, 7, 16, 49, 6</x:Anchor>
   <x:AutoFill>False</x:AutoFill>
   <x:Row>34</x:Row>
   <x:Column>5</x:Column>
   <x:RowHidden/>
  </x:ClientData>
 </v:shape></xml>


  Problem (<br>-Tag): 
  <v:textbox style='mso-direction-alt:auto' o:singleclick="f">
   <div style='text-align:center'><font face="Calibri" size="220"
   color="#000000">PDF<span style='mso-spacerun:yes'>  </span>für alle Händler
   exportieren<br>
      </font></div>
  </v:textbox>

  // the <br> inside the font will create the issue.
 // workaround
    private function loadZip(string $filename, string $ns = ''): SimpleXMLElement
    {
        $contents = $this->getFromZipArchive($this->zip, $filename);
        $rels = simplexml_load_string(
            str_replace('<br>', '<br/>', $this->securityScanner->scan($contents)), // quick fix 
            //$this->securityScanner->scan($contents),
            'SimpleXMLElement',
            Settings::getLibXmlLoaderOptions(),
            $ns
        );

        return self::testSimpleXml($rels);
    }
```

### What features do you think are causing the issue

- [X ] Reader

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
- xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
newest

### PR DESCRIPTION
**Pull request by oleibman**
This is a replacement for draft PR #2455 and draft PR #3127. There is some useful commentary in those PRs which I have mostly, but not entirely, duplicated below. Fix #2396. Fix #1770. Fix #2388. Fix #2904. Issue #3147 concerns an ODS file, so is not helped by this PR.

This fix allows form control elements to be read in and written out. It does not allow you to add such elements, nor even to locate them or determine their properties (so you can't modify or delete them). Although it handles reading and writing of sheets containing both form controls and comments, it will probably create a corrupt spreadsheet if you try adding a new comment to a sheet with form controls - probably quite difficult to solve. Cloning the sheet probably won't work either - probably easier than the other. It is conceivable that we want to add a new property to the Xlsx Reader which turns the reading of form elements on or off (default=off), so that negative effects will be limited to those who have explictly opted in. The change in its current form does not implement such a property.

A related problem is that the vml files used for the form controls sometimes contain invalid xml. Fix #3125 (rejected previous PR #1181 as too risky, issue was also reported as #170). Vml file should be valid Xml, but Excel can generate unclosed `<br>` tags, preventing Xlsx reader from reading file correctly. I believe a very narrowly targeted fix, changing `<br>` to `<br/>`, and only when reading vml files, probably mitigates the risk. The sample file formscomments.xlsx which is part of this change shows this problem with `Button 1` on sheet `Forms`; the spreadsheet was created with Excel 365, so the problem is not restricted to Excel 2013 as originally reported. A comment on PR 3127 indicates that other tags might be involved, but, without a file demonstrating that, I will restrict this change to br tags for now.

I am starting this out in draft status, and will probably leave it that way for some time. I'm not sure where we want to go with this. It fixes some problems, but in a limited manner, and creates some others. I'm not sure the pain of the others is balanced considering the limitations of the fix. If enough interest is generated as a result of this ticket being out there, we can proceed; if not, it probably isn't worth it.

Because of its limitations, the change isn't really testable. As in some other recent installs, I have added a sample to demonstrate that it works correctly.

As it turns out, if we have a worksheet which contains both form controls and comments (see formscomments.xlsx which is part of this PR), PhpSpreadsheet already creates a corrupt file when it tries to load and save the spreadsheet with such a worksheet. With this change, the file is saved without corruption. This tilts things in favor of proceeding. I'm still not ready, but this will be an important consideration.

A sample file for issue #2621 illustrated a problem with shape files. Since they are involved here, I took a look at how the sample worked with this code. In master, and with this change, a corrupt file results. Fixing that is probably easier than the general problem of handling shape files, but it's an argument against moving this forward until the corruption problem can be addressed.

Fix #2661. A template including checkboxes was leading to file corruption solved by this PR. Another argument for moving forward.

This is:

```
- [x] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests
```

Checklist:

- [x] Changes are covered by samples
  - [ ] Changes are covered by existing unit tests
  - [x] New samples have been added
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [x] Documentation is updated as necessary

### Why this change is needed?

Provide an explanation of why this change is needed, with links to any Issues (if appropriate).
If this is a bugfix or a new feature, and there are no existing Issues, then please also create an issue that will make it easier to track progress with this PR.

### CODE REVIEW

**Comment by fglueck** [comment]
Please note that also other tags do not need a close tag either.

$contents = str_replace('<br>', '<br/>', $contents);

Can't be the final solution. I fixed this by using tidy with xml flag. But tidy will change/extend the dependencies of phpSpreadsheet.

**Comment by oleibman** [comment]
@fglueck We have seen the problem repeatedly with unclosed `br` tag. You are the only one who has implicated other tags. If you have a sample file to share, I can see if I can handle them. Without a sample, my hands are tied.

**Comment by oleibman** [comment]
@MarkBaker @PowerKiKi After being in draft status since last December, I think it is time to move this into ready status. I probably won't merge it till after Php8.2 goes live, and can delay for any milestones you wish (PhpSpreadsheet 1.26 or 2.0). My thinking is that it solves some problems, and probably doesn't cause any new ones (possibly wishful thinking but the test suite survives it and it seems to solve existing and new forms-related issues). It could lead to more problem reports eventually (for things which won't work without it anyhow); as people become aware that it's available, they are sure to do things which will break it. I have added a caveat to this effect to the official documentation.

**Comment by oleibman** [comment]
@MarkBaker Now that Php8.2 and PhpSpreadsheet 1.26 are real, I think I might want to merge this next week, probably Tuesday or Wednesday. I know a couple of my recent changes have given you heartburn on the PhpSpreadsheet 2.0 front. Do you think this one will be similarly problematic? If so, I will revert to draft status rather than merging.

**Comment by edeebee** [comment]
Is there an approximate date, when this fix will be released?

**Comment by Ericcscro5** [comment]
Hello.  With this merged, is there a way to read checkboxes in a sheet?

**Comment by oleibman** [comment]
@Ericcscro5 Sorry, I was not able to come anywhere close to figuring out how to implement some obviously useful additions to this change, including your question. As the description stated, "This fix allows form control elements to be read in and written out. It does not allow you to add such elements, nor even to locate them or determine their properties (so you can't modify or delete them)."

**Comment by oleibman** [comment]
@Ericcscro5 Sorry, I was not able to come anywhere close to figuring out how to implement some obviously useful additions to this change, including your question. As the description stated, "This fix allows form control elements to be read in and written out. It does not allow you to add such elements, nor even to locate them or determine their properties (so you can't modify or delete them)."

**Comment by Ericcscro5** [comment]
> @Ericcscro5 Sorry, I was not able to come anywhere close to figuring out how to implement some obviously useful additions to this change, including your question. As the description stated, "This fix allows form control elements to be read in and written out. It does not allow you to add such elements, nor even to locate them or determine their properties (so you can't modify or delete them)."

Thank you  for the reply.  

I just worked around this by linking the checkbox to a cell, setting that linked cell's text color equivalent to its background and then reading the linked cell's value.

**Pull request merged**
