### PR TITLE
SCA with Php Inspections (EA Extended): bug-fixes

### PR DESCRIPTION
**Pull request by kalessil**
Regular FR pattern is no applicable, unfortunately, please review the PR content.
I applied only essential changes reported by Php Inspections (EA Extended).

### CODE REVIEW

**Comment by PowerKiKi** [comment]
What do you mean by "Regular FR pattern is no applicable" ?

**Comment by kalessil** [comment]
This: https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

**Comment by kalessil** [comment]
ping @PowerKiKi

**Comment by vladyslavstartsev** [comment]
@kalessil I think @PowerKiKi didn't understood you because you wrote `FR pattern` first, and not `PR pattern`

**Comment by kalessil** [comment]
Oops, it suppose to be PR (Pull Request) of course

**Comment by kalessil** [comment]
Awesome, thank you @PowerKiKi 👍

**Comment by PowerKiKi** [comment]
Thanks to you. I was not aware of this tool. I'll have to give it a try, that looks very interesting...

**Comment by treadmillian** [comment]
I use this with my IDE PhpStorm, very useful.

**Comment by kalessil** [comment]
Great to hear that =)

**Pull request merged**
