### PR TITLE
Resolve XSS Vulnerability in the HTML Writer

### PR DESCRIPTION
**Pull request by MarkBaker**
This is:

```
- [X] a bugfix
- [ ] a new feature
```

Checklist:

- [X] Changes are covered by unit tests
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [X] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

To prevent a potential XSS attack when loading a spreadsheet from an unknown source and saving as HTML

### CODE REVIEW

**Comment by pandeydhirendra** [comment]
Hi Team,

We are using this library with version (1.10.0) in one of our projects. Request you to please release this fix in a stable version.
Thanks in advance.

**Comment by shahariaazam** [comment]
Can we ship this PR to older branch like `1.8.x` and release a patch? Because 1.8.2 support PHP 5.6 and 7.0. There are lots of application that are still using PHP7.0 and that requires this fixing.

So what about we can apply this to 1.8.2 and create a new release for 1.8.3? For me, it's kind of important. I already applied this patch on 1.8.2. Check https://github.com/PHPOffice/PhpSpreadsheet/compare/1.8.2...shahariaazam:xss-fix-for-1.8.2?expand=1

**Comment by j4nr6n** [comment]
Same question but for 1.12, which is the latest release that supports PHP 7.1.

**Comment by deepti4666** [comment]
I have this issue for 1.15.0 

image

**Pull request merged**
