### PR TITLE
Namespacing Phase 2 - Styles

### LINKED ISSUE #2494: Duplicating worksheet is not copying styling
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Expecting a worksheet to be fully duplicated using this code

$clonedWorksheet = clone $spreadsheet->getSheetByName('Worksheet 1');
$clonedWorksheet->setTitle('Copy of Worksheet 1');
$spreadsheet->addSheet($clonedWorksheet);

### What is the current behavior?

Some cell styles like fills and font colors are not copied over

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php
	$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
	$spreadsheet = $reader->load('Elevation.xlsx');

	$new_elevation = clone $spreadsheet->getActiveSheet();
	$new_elevation->setTitle('Max Potential');
	$spreadsheet->addSheet($new_elevation);

	$spreadsheet->setActiveSheetIndexByName('Max Potential');

	$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
	$writer->save('php://output');
```

### Which versions of PhpSpreadsheet and PHP are affected?

1.21
[Elevation.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7842554/Elevation.xlsx)

### PR DESCRIPTION
**Pull request by oleibman**
This is part 2 of a several-phase process to permit PhpSpreadsheet to handle input Xlsx files which use unexpected namespacing. The first phase, introduced as part of release 1.19.0, essentially handled the reading of data. This phase handles the reading of styles. More phases are planned.

It is my intention to leave this in draft status for at least a month. This will give time for additional testing, by me and, I hope, others who might be interested.

This fixes the same problem addressed by PR #2458, if it reaches mergeable status before I am ready to take this out of draft status. I do not anticipate any difficult merge conflicts if the other change is merged first.

My major non-standard unit test file had disabled any style-related tests when phase 1 was installed. These are now all enabled.

After commit 2d389f5 on Jan. 12, 2022, fix #2494.

This is:

```
- [x] a bugfix
- [x] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### CODE REVIEW

**Comment by oleibman** [comment]
Scrutinizer reports 3 minor errors. Its analysis is faulty in all 3 cases. A SimpleXMLElement can be falsey, e.g. `simplexml_load_string('<root />')`. Function preg_replace (2 times) can return other than string (array or null).

**Comment by oleibman** [comment]
Readied for review after a month in draft status. My plan is to wait at least 2 weeks before merging.

**Comment by oleibman** [comment]
Per my previously-announced schedule, I will attempt to merge this PR tomorrow morning (US Pacific).

**Comment by daedeloth** [comment]
Thank you! Sorry for not following up, other stuff got in the way :)

**Pull request merged**
