### PR TITLE
Fix bug #1626 where values of 0 were "rounded" up/down as if they were not 0

### LINKED ISSUE #1626: ROUNDDOWN and ROUNDUP return incorrect results for values of 0
This is:

```
- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Values of 0 should stay 0 when either rounded up or down.

### What is the current behavior?
Values of 0 are "rounded" down/up as if they were not 0.

### What are the steps to reproduce?
The following code produces output `-0.01 0.01` instead of `0 0`:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

echo \PhpOffice\PhpSpreadsheet\Calculation\MathTrig::ROUNDDOWN(0, 2).' ';
echo \PhpOffice\PhpSpreadsheet\Calculation\MathTrig::ROUNDUP(0, 2).' ';
```

### What could be a possible solution?
A possible solution could be to explicitly handle values of zero. In `ROUNDUP`, for example, the code could be something like this:
```php
        if ((is_numeric($number)) && (is_numeric($digits))) {
            if ($number == 0.0) {
                return 0.0;
            }

            if ($number < 0.0) {
                return round($number - 0.5 * 0.1 ** $digits, $digits, PHP_ROUND_HALF_DOWN);
            }

            return round($number + 0.5 * 0.1 ** $digits, $digits, PHP_ROUND_HALF_DOWN);
        }
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.14.1
PHP 7.2.20

### PR DESCRIPTION
**Pull request by Flinsch**
This is:

```
- [X] a bugfix
- [ ] a new feature
```

Fixes #1626 

Checklist:

- [X] Changes are covered by unit tests
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [X] CHANGELOG.md contains a short summary of the change
- [X] Documentation is updated as necessary (not necessary)

### Why this change is needed?
Values of 0 should stay 0 when either rounded up or down.

### CODE REVIEW

**Comment by Flinsch** [comment]
#1626

**Comment by Flinsch** [comment]
Sorry for two commits with identical comments.

**Comment by MarkBaker** [comment]
Thank you for catching the error, and for the fix

Watch when you're updating the change log though, that you tag your change in the `## Unreleased - TBD` section rather than against a previous release

**Comment by Flinsch** [comment]
> Thank you for catching the error, and for the fix
> 
> Watch when you're updating the change log though, that you tag your change in the `## Unreleased - TBD` section rather than against a previous release

Oh yes, sorry for the confusion. And thank you very much too!

**Pull request merged**
