### PR TITLE
:wastebasket: Deprecate `IReader::SKIP_EMPTY_CELLS`

### PR DESCRIPTION
**Pull request by homersimpsons**
This is an alias to `IGNORE_EMPTY_CELLS` there is no point to have both.

This is:

- [-] a bugfix
- [-] a new feature
- [x] refactoring
- [-] additional unit tests

Checklist:

- [x] Changes are covered by unit tests
  - [x] Changes are covered by existing unit tests
  - [-] New unit tests have been added
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change and a link to the pull request if applicable
- [x] Documentation is updated as necessary

### Why this change is needed?

`IReader::SKIP_EMPTY_CELLS` is an alias to `IGNORE_EMPTY_CELLS` there is no point to have both.

I have some questions:
1. Should I prepare the merge request for 3.0?
    1. If yes, Which branch should I target?
2. Should I deprecate + remove, or can I remove it directly in 3.0?

(Maybe this change is not wanted, but I feel like having both options is confusing)

### CODE REVIEW

**Comment by oleibman** [comment]
There is a point to have both. This would be a breaking change for people who use SKIP_EMPTY_CELLS. I would need to hear why you think the improvement offered by this change outweighs the problems that it would cause.

**Comment by homersimpsons** [comment]
> There is a point to have both. This would be a breaking change for people who use SKIP_EMPTY_CELLS.

I suggest to remove it in 3.0. It should be rather straightforward to search and replace this through a codebase.

> I would need to hear why you think the improvement offered by this change outweighs the problems that it would cause.

1. The documentation sometimes refers `IGNORE_EMPTY_CELLS` and sometimes `SKIP_EMPTY_CELLS`, a user may not be aware they are the same.
2. In a codebase seeing both may lead to confusion while they are actually the same.
3. Seeing the same value defined for both made me think there was a mistake at first.
4. In this library code we were comparing twice with the same value, this is an example of the kind of confusion this creates

Of course there are no strong disadvantages, and the breaking change may not be worth. But I think having only one way to do things is less error prone.

**Comment by oleibman** [comment]
I would have no problem with making it clear in the documentation that these are aliases of each other. I will note, however, that the online documentation already does this:
```
$reader::SKIP_EMPTY_CELLS (synonym for IGNORE_EMPTY_CELLS)
```
But there is no doc-block where the constants are defined which emphasizes this point; I would have no trouble if you wanted to add that. I wouldn't even have a problem if you wanted to mark one of them deprecated in its doc-block so that it can be removed in a *future* release. Likewise, if you wish to make the examples consistently use one and not the other, I would have no problem with that. And I certainly have no problem with your changing BaseReader to perform only one test (assuming it still passes the unit test suite, which I'm confident it would). But you can do all of that without causing a break, which I think is just too high a cost for too little benefit, especially considering that there is no notice beforehand.

So, please restore the deleted item in your PR, make the changes mentioned in the previous paragraph, and I will be glad to consider it then.

**Comment by oleibman** [comment]
I cannot entertain deleting the redundant variable as part of imminent 3.0.0 with no notice. (Your changes did not delete it, but your explanatory text indicated that you wanted to.) However, I am okay with declaring it deprecated, and your other changes. I will, unfortunately, not be able to merge this change till after 3.0.0; my plate is overflowing till then. Please change your deprecation line to:
```php
@deprecated 3.1.0 use IGNORE_EMPTY_CELLS instead
```
I will update it if it can be installed earlier, or needs to wait longer. Also, please add a doc-block for IGNORE_EMPTY_CELLS.

I believe your php-cs-fixer problem is that the doc-block summaries need to end with a period (not my rule, I'm just here to explain). So "Flag used to load any charts that are defined (if the Reader supports Charts).", etc., should be accepted. Note that this rule applies only to summary text, and not, for example, to the `@deprecated` tag.

**Comment by homersimpsons** [comment]
> I cannot entertain deleting the redundant variable as part of imminent 3.0.0 with no notice. (Your changes did not delete it, but your explanatory text indicated that you wanted to.) However, I am okay with declaring it deprecated, and your other changes. I will, unfortunately, not be able to merge this change till after 3.0.0; my plate is overflowing till then. 

Done

> Also, please add a doc-block in IReader for IGNORE_EMPTY_CELLS. (And, optionally, for IGNORE_ROWS_WITH_NO_CELLS.)

Done, I'm not entirely sure about the documentations wordings. Also, there are 3 sources of documentations: the md doc, the flag doc, the getter doc. Maybe the flag doc could refer the getters doc (or vice versa) ?

> I believe your php-cs-fixer problem is that the doc-block summaries need to end with a period (not my rule, I'm just here to explain). So "Flag used to load any charts that are defined (if the Reader supports Charts).", etc., should be accepted.

Thank you!

**Comment by oleibman** [comment]
Thank you for your contribution.

**Pull request merged**
