### PR TITLE
add date format `dd-mm-yyyy` in NumberFormat.php

### PR DESCRIPTION
**Pull request by JaberWiki**
added FORMAT_DATE_DDMMYYYYMINUS = 'dd-mm-yyyy'

This is:

- [ ] a bugfix
- [*] a new feature
- [ ] refactoring
- [ ] additional unit tests

Checklist:

- [ ] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [ ] New unit tests have been added
- [*] Code style is respected
- [ ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change and a link to the pull request if applicable
- [ ] Documentation is updated as necessary

### Why this change is needed?

To use data format of 'dd-mm-yyyy'

### CODE REVIEW

**Comment by oleibman** [comment]
You can already use this format:
```php
$sheet->getStyle('A1')->getNumberFormat()->setFormatCode('dd-mm-yyyy');
```
That doesn't seem appreciably more difficult than:
```
$sheet->getStyle('A1')->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_DATE_DDMMYYYYMINUS);
```
So, the question is, "Do we want to support a new pre-defined format?" I personally am not in favor of adding yet another ambiguous date format (e.g. you can't tell at a glance what date 01-02-2024 is). Such formats lead to problems for us, and for the users of spreadsheets on which they are found. I will, however, leave this PR open for a while to see if others think this would be a good addition.

**Comment by JaberWiki** [comment]
> You can already use this format:
> 
> ```
> $sheet->getStyle('A1')->getNumberFormat()->setFormatCode('dd-mm-yyyy');
> ```
> 
> That doesn't seem appreciably more difficult than:
> 
> ```
> $sheet->getStyle('A1')->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_DATE_DDMMYYYYMINUS);
> ```
> 
> So, the question is, "Do we want to support a new pre-defined format?" I personally am not in favor of adding yet another ambiguous date format (e.g. you can't tell at a glance what date 01-02-2024 is). Such formats lead to problems for us, and for the users of spreadsheets on which they are found. I will, however, leave this PR open for a while to see if others think this would be a good addition.

image
On Laravel `Maatwebsite\Excel` package, I can use this as `NumberFormat::FORMAT_DATE_DDMMYYYYMINUS`

**Comment by JaberWiki** [comment]
> You can already use this format:
> 
> ```
> $sheet->getStyle('A1')->getNumberFormat()->setFormatCode('dd-mm-yyyy');
> ```
> 
> That doesn't seem appreciably more difficult than:
> 
> ```
> $sheet->getStyle('A1')->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_DATE_DDMMYYYYMINUS);
> ```
> 
> So, the question is, "Do we want to support a new pre-defined format?" I personally am not in favor of adding yet another ambiguous date format (e.g. you can't tell at a glance what date 01-02-2024 is). Such formats lead to problems for us, and for the users of spreadsheets on which they are found. I will, however, leave this PR open for a while to see if others think this would be a good addition.

image

On Laravel `Maatwebsite\Excel` package, I can use this as `NumberFormat::FORMAT_DATE_DDMMYYYYMINUS`

**Comment by Illusionist3886** [comment]
Great Finding 🤯
@JaberWiki

**Comment by Illusionist3886** [comment]
I wanted to take a moment to highlight the significance of this PR, especially for those of us who frequently work with Excel exports in Laravel. The addition of customizable date formats, specifically the dd-mm-yyyy format, represents a pivotal improvement in the Laravel Excel package.

**Comment by MarkBaker** [comment]
Can you explain why it's so significant?
`NumberFormat::FORMAT_DATE_DDMMYYYYMINUS` is nothing more than a pre-defined string constant. You could use the string, where the format mask value is clearly visible in your own code; or define that constant anywhere within your own code, where it would be more significant because it relates to the spreadsheets that you are creating.

**Comment by PowerKiKi** [comment]
I also fail to see how this bring any value to PhpSpreadsheet. We cannot reasonably declare a constant for every possible format out there. But you can, in your own projects, according to the specific need of your specific use-cases.

 IMHO we already have too many of them. We should try to decrease them, not increase them.

**Pull request closed without merging**
