### PR TITLE
clean drawing from active worksheet

### PR DESCRIPTION
**Pull request by holacliente**
This is:

```
- [ ] a bugfix
- [ x] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

Sometimes we need show the excel without images

### CODE REVIEW

**Comment by holacliente** [comment]
i so hope it will be added, because i was looking for this method

**Review by MarkBaker — CHANGES_REQUESTED** [review]
Thank you for this addition

Can you set gitignore for the sublime settings

**Comment by holacliente** [comment]
> Thank you for this addition
> 
> Can you set gitignore for the sublime settings

Sorry for it, i will fix it

**Comment by PowerKiKi** [comment]
Thank you for the contribution. However I don't think this need to be added because you can get the same result without any change in PhpSpreadsheet:


```php
<?php

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->getDrawingCollection()->exchangeArray([]);
```

**Pull request closed without merging**
