### PR TITLE
Prevent color palette changing

### PR DESCRIPTION
**Pull request by al-lala**
This is:

- [X] a bugfix
- [ ] a new feature

Checklist:

- [ ] Changes are covered by unit tests
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

What does it change?
Don't create color in palette when already exist.

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Could you please explain why this should be done ? what happened before this modification ?

Also it will need to be covered by unit tests to be merged.

**Comment by al-lala** [comment]
> Sorry for my bad english ( i'm frech ) :

**Before :** 
Palette colors are changed systematicaly when color are find in workbook.
Original palette setting are useless in this case.

**After :** 
Palette colors are preserved if colors already exist in initial palette.
Original palette setting are used and conserved.

**This resolve this issue :** 
If you copy sheet from xls file saved by phpspreadsheet to other xls file, the colors changes.

**Unit tests**
For me, new unit test are unnecessary.

**Comment by PowerKiKi** [comment]
Thanks for the explanation, I understand better the reason for the change. However unit tests are important to prevent regression in the future. I won't be able to merge without unit tests. It could be as simple as writing a file, reading it and checking the color palette.

**Comment by al-lala** [comment]
I have correct an error and make Unit Tests.

> Thanks for PHPOffice/PHPSpreadsheet, this is the best way to read/write Excel in php context.

**Comment by PowerKiKi** [comment]
Thank you, I made a few minor tweaks and merged it.

**Pull request closed without merging**
