### PR TITLE
Possible fix for issue #3337

### PR DESCRIPTION
**Pull request by fdjohnston**
Using the `FunctionPrefix::addFunctionPrefixStripEquals` appears to fix the issue by adding the _xlfn prefix to functions in array formulas.

This is:

- [x] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests

Checklist:

- [ ] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [ ] New unit tests have been added
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change and a link to the pull request if applicable
- [ ] Documentation is updated as necessary

### Why this change is needed?

Addresses issue #3337.

I didn't write any unit tests since I wasn't sure how to test the underlying XML output by the writer.  Happy to take a crack at it if you have any tips.

### CODE REVIEW

**Comment by fdjohnston** [comment]
Thanks for the recommendation.  I started with a couple simple cases.  These can be expanded upon if necessary, though based on @MarkBaker comments back in issue #3337 it sounds like this is all getting overhauled in the next major version of PhpSpreadsheet anyway.

**Comment by MarkBaker** [comment]
> based on @MarkBaker comments back in issue #3337 it sounds like this is all getting overhauled in the next major version of PhpSpreadsheet anyway.

That doesn't change the need to write the function prefix though

**Comment by fdjohnston** [comment]
Totally agree.  Was just suggestion that a couple of simpler tests is probably adequate.

**Comment by fdjohnston** [comment]
But of course that's up to you.  Happy to add others if you feel it's necessary.

**Pull request merged**
