### PR TITLE
issue #94 fix xslm parsing issue (null object for imageData)

### PR DESCRIPTION
**Pull request by alexmilde**

### CODE REVIEW

**Comment by PowerKiKi** [comment]
I think it would be more readable to `continue;` early instead of nesting the whole block inside the `if`.

Also did you identify why the data was missing in the first place ?

**Comment by alexmilde** [comment]
`$shape->xpath('//v:imagedata');`
seems to return null as far as i recall.

my testfile which caused the error is rather complex - so i cant really pin it down.

so you prefer:
`                                                if ($imageData) {
                                                  continue;
                                                }`

**Comment by PowerKiKi** [comment]
yeap, `if ($imageData) { continue; }` [would be nice](http://softwareengineering.stackexchange.com/a/18459/85361) IMHO.

**Comment by alexmilde** [comment]
well its opinion based, but i will change it ;)

**Comment by PowerKiKi** [comment]
Much easier to review, thank you !

**Comment by alexmilde** [comment]
your welcome. 
btw: this was my first PR ;) 
do you delete the branch or shall i?

**Comment by PowerKiKi** [comment]
You should do it if you don't need anymore.

**Pull request merged**
