### PR TITLE
fix: allow iterators to go out of bounds with prev()

### PR DESCRIPTION
**Pull request by dkarlovi**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [x] CHANGELOG.md contains a short summary of the change
- [x] Documentation is updated as necessary

### Why this change is needed?

See #587.

### CODE REVIEW

**Comment by dkarlovi** [comment]
Build failure unrelated.

**Comment by dkarlovi** [comment]
@PowerKiKi @MarkBaker could you please have a look here?

**Comment by PowerKiKi** [comment]
Merged with fixes and better tests

**Comment by dkarlovi** [comment]
@PowerKiKi do you think we could get a bugfix release?

**Comment by PowerKiKi** [comment]
I try to release roughly monthly-ish, so most likely in a week or so

**Comment by dkarlovi** [comment]
That sounds great, thank you @PowerKiKi :+1:

**Comment by dkarlovi** [comment]
Hopefully you get the time to do it soonish. :1st_place_medal:

**Pull request closed without merging**
