### PR TITLE
Very Minor Simplification to Matrix Functions

### PR DESCRIPTION
**Pull request by oleibman**
The external Matrix library has introduced some changes which permit the matrix functions to be slightly simplified.

This is:

```
- [ ] a bugfix
- [ ] a new feature
- [x] code simplification
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### CODE REVIEW

**Comment by oleibman** [comment]
@MarkBaker @PowerKiKi 
Any idea what's going wrong with the PHP8.1 setup? Two attempts, same failure both times.
image

**Comment by MarkBaker** [comment]
Something in the nightly build has broken composer:
```
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:286
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/WritableArrayRepository.php:286
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/InstalledFilesystemRepository.php:286
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
/home/runner/.cache/composer/files
```

**Comment by MarkBaker** [comment]
Looks like Jordi is already aware of [the issue #10008](https://github.com/composer/composer/issues/10008) and has created a fix; but the CI runner is using shivammathur's PHP setup, which is daily cached, so hasn't yet picked up the composer fixes... hopefully it should have resolved itself by tomorrow.

I just wish that Github Actions provided a rerun button for failed pipeline tasks, rather than requiring a new push to trigger a run

**Comment by MarkBaker** [comment]
shivammathur indicates that he's changed his cache settings for the PHP setup, so it should now be good to pick up the changes to composer for deprecations

**Comment by oleibman** [comment]
Thanks, it all works now. However, it looks like 8.1 has thrown us a new monkey wrench; need a small fix to Worksheet Iterator (add explicit typehint for return type for ```valid```) before 8.1 goes live.

**Comment by MarkBaker** [comment]
The good news is that there's a lot less problems (so far) with 8.1 than there were with 8.0

**Pull request merged**
