### PR TITLE
Update reading-and-writing-to-file.md

### PR DESCRIPTION
**Pull request by athena-metis**
Added a note to the documentation about formulas still being calculated where column autosizing is turned on, even if pre-calculation is set to false. This is true at least for the Xlsx writer but probably others to if they use calculateColumnWidths from Worksheet/Worksheet.php

This is:

```
- [ ] a bugfix
- [ ] a new feature
- [X] a documentation addition 
```

Checklist:

- [ ] Changes are covered by unit tests
- [ ] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [X] Documentation is updated as necessary

### Why this change is needed?
Explains somewhat unexpected behaviour (you can see why it happens but may not consider it initially)

### CODE REVIEW

**Comment by oleibman** [comment]
Very interesting observation. Might it be possible for you to write a formal test which demonstrates the behavior that you are documenting?

**Comment by MarkBaker** [comment]
The reason for this is that automatic column sizing should be based on the display value of the cells, which includes formatting (font size, format masking, etc) and when a cell contains a formula, the style settings need to be applied to the calculated value for that formula rather than the formula itself

**Comment by oleibman** [comment]
It appears that there are no tests for pre-calculation false. So, I will write some, bearing this change in mind, and move this change forward.

**Comment by oleibman** [comment]
@athena-metis , thank you for your contribution.

**Pull request merged**
