### PR TITLE
Add "outputEncoding" property to Writer/Csv.php

### PR DESCRIPTION
**Pull request by AkiraPenguin**
Add "outputEncoding" property.
"outputEncoding" property is used by mb_convert_encoding function.
Default value is '' (mb_internal_encoding).

This is:

```
- [ ] a bugfix
- [ *] a new feature
```

Checklist:

- [* ] Changes are covered by unit tests
- [ ] Code style is respected
- [* ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?
I often convert worksheets to CSV and import them into Japanese applications.
Mainly Japanese applications on Windows require that the CSV to be imported is Shift JIS.
Thank you.

### CODE REVIEW

**Comment by AkiraPenguin** [comment]
Sorry, check on "Changes are covered by unit tests" is wrong.
I tested it manyally.

**Comment by oleibman** [comment]
Can you add formal unit test(s) to cover your change? Write a temporary file, read it back in (possibly via file_get_contents), verify that the data is encoded as expected, and delete the temporary file.

**Comment by AkiraPenguin** [comment]
OK.
The unit test is complete.

**Comment by oleibman** [comment]
I do not see a new test. Did you push your change after including it? Also, my apologies for not mentioning it earlier, but please update docs/topics/reading-and-writing-to-file.md to describe the use of your new method.

**Comment by AkiraPenguin** [comment]
I am sorry.
I finally realized that I needed to test with PHPUnit.
I used PHPUnit firsttime.
I am not sure if the submission is what you want, so please check.
Thank you.

**Comment by oleibman** [comment]
This is quite close to what is needed. We want to test the actual characters in the file to be sure they have been encoded correctly. I believe that the UTF-8 encoding of your Japanese characters (or at least some contiguous part of them) is:
`"\xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf\xef\xbc\x81"`
Likewise, I believe that the Shift_JIS encoding of the characters contains:
`"\x82\xb1\x82\xf1\x82\xc9\x82\xbf\x82\xcd\x81\x49"`
You should take those encodings with a grain of salt; if I'm wrong, that will show up in your unit tests. At any rate, once you've done your file_get_contents, you can now test if the contents contain the expected data either by using strpos and asserting that its result is not false, or by using assertStringContainsString.

**Comment by AkiraPenguin** [comment]
I have fixed it.
Thank you for your polite guidance.

**Pull request merged**
