### PR TITLE
fix #1114 issue

### LINKED ISSUE #1114: Fatal error when loading file
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The file can be loaded correctly. 
If not, produce an elegant error instead an undefined index + fatal error.

### What is the current behavior?
The library produce a fatal error :

```
Undefined offset: 3 in phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php in readLabelSst at line 3810
```
followed by
```
__clone method called on non-object in phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php in readLabelSst at line 3810
```

### What are the steps to reproduce?
Just reading an XLS file (probably corrupted).
I can't provide this file as it contains sensible informations.

### Which versions of PhpSpreadsheet and PHP are affected?
We are actually using version 1.6.0 for PhpSpreadSheet 
I'll try a bit later on latest version.

PHP : 7.3.6

### PR DESCRIPTION
**Pull request by tezrik**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

Fixed #1114 issue

### CODE REVIEW

**Comment by oleibman** [comment]
Can you add a unit test which (a) fails without your change and (b) succeeds with your change?

**Comment by tezrik** [comment]
I add test

**Comment by oleibman** [comment]
Thanks. I plan to merge this in a few days. In the meantime, can you please expand on this comment "this has to do with that index 4 is omitted in all BIFF versions for some strange reason ... check the OpenOffice documentation of the FONT record"? If there is something in the official documentation, I would just like to include it with this PR. You can just include it as a comment in the PR; not necessary to add it to the source code.

**Comment by tezrik** [comment]
I remove comment about "index in all biff version". In documentation OpenOffice not explanations on issue #1114.

**Pull request merged**
