### PR TITLE
Add two cell anchor drawing

### PR DESCRIPTION
**Pull request by naotake51**
This is:

```
- [ ] a bugfix
- [x] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [x] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

PhpSpreadsheetを使用して、セルの中央に画像を配置したいです。
twoCellAnchorタグによる画像の配置ができると助かります。

I want to use PhpSpreadsheet to center the image in a cell.
It would be helpful if there was an image arrangement by twoCellAnchor tag.

sample code
```php
// A position relative to a cell (top-left) and sized relative to another cell (bottom right)
$drawing = new Drawing();
$drawing->setName('Green Square');
$drawing->setPath('tests/data/Writer/XLSX/green_square.gif');
$drawing->setCoordinates('A1');
$drawing->setOffsetX(30);
$drawing->setOffsetY(10);
$drawing->setCoordinates2('E8');
$drawing->setOffsetX2(-50);
$drawing->setOffsetY2(-20);
$drawing->setWorksheet($sheet);
```

スクリーンショット 2022-01-27 1 25 07

output xl/drawings/drawing1.xml
```xml
<xdr:twoCellAnchor>
    <xdr:from>
        <xdr:col>0</xdr:col>
        <xdr:colOff>285750</xdr:colOff>
        <xdr:row>0</xdr:row>
        <xdr:rowOff>95250</xdr:rowOff>
    </xdr:from>
    <xdr:to>
        <xdr:col>4</xdr:col>
        <xdr:colOff>-476250</xdr:colOff>
        <xdr:row>7</xdr:row>
        <xdr:rowOff>-190500</xdr:rowOff>
    </xdr:to>
    <xdr:pic>
        ...
        <xdr:spPr>
            <a:xfrm>
                <a:off x="25400" y="812800" />
                <a:ext cx="4940300" cy="3765550" />
            </a:xfrm>
            <a:prstGeom prst="rect">
                <a:avLst />
            </a:prstGeom>
        </xdr:spPr>
    </xdr:pic>
    <xdr:clientData />
</xdr:twoCellAnchor>
```
---
また、twoCellAnchorタグのxlsxファイルを読み込み、そのまま書き出すとoneCellAnchorに変わってしまうため、画像の配置が変わってしまう問題があります。

Also, if you import an xlsx file with twoCellAnchor tag and export it as is, it will be changed to oneCellAnchor, which will change the placement of the image.

```php
// read twoCellAnchor tag image.
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('./input.xlsx');

// written oneCellAnchor tag image.
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, "Xlsx");
$writer->save("./output.xlsx");
```

[input.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8161848/input.xlsx)
スクリーンショット 2022-01-27 14 03 32
output.xlsx
スクリーンショット 2022-01-27 14 03 37

### CODE REVIEW

**Comment by oleibman** [comment]
Not sure why you closed this. If it was because there had been no action on it, my apologies for the delay. I am ready to review it now if you wish to reopen it.

**Comment by naotake51** [comment]
My apologies.
I didn't have any experience with OOS, so I thought it meant I was rejected.
I would appreciate it if you could take a look.

**Comment by oleibman** [comment]
I probably won't be able to get to this for a few days. In the meantime, I would like to suggest an enhancement. In Xlsx, two-cell anchor drawings are associated with an `editAs` attribute (`twocell` or `onecell` or `absolute`). It would be useful if you could add that to the Drawing class, and to the Xlsx Reader and Writer.

**Comment by naotake51** [comment]
@oleibman

I understood it to mean adding `absolute` drawing.
I will take a look at Apache POI as it may be helpful.
https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/usermodel/XSSFClientAnchor.html

**Comment by oleibman** [comment]
Thank you for your contribution.

**Comment by naotake51** [comment]
> I probably won't be able to get to this for a few days. In the meantime, I would like to suggest an enhancement. In Xlsx, two-cell anchor drawings are associated with an editAs attribute (twocell or onecell or absolute). It would be useful if you could add that to the Drawing class, and to the Xlsx Reader and Writer.

Sorry, I couldn't take the time to proceed.

**Pull request merged**
