### PR TITLE
fix: issue #1476 crash with numeric string value terminating with new line

### LINKED ISSUE #1476: Crash while trying setting a cell the value "123456\n"
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
```$worksheet->setCellValueByColumnAndRow(1,1,"123456\n");```
Should add the value "123456\n" (or better the number 123456) to the cell at indexes 1,1

### What is the current behavior?
the DefaultValueBinder::dataTypeForValue matches (with the preg_match case) the value as a DataType::TYPE_NUMERIC and then the Cell->setValueExplicit crashes during the check ```if (is_string($pValue) && !is_numeric($pValue))```

### What are the steps to reproduce?
Try to set to a cell a value with the ```\n``` at the end, for example:
$worksheet = //Worksheet instance
$worksheet->setCellValueByColumnAndRow(1,1,"123456\n");

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(1,1,"123456\n");


### Which versions of PhpSpreadsheet and PHP are affected?
v1.12.0

### PR DESCRIPTION
**Pull request by giannign1**
This is:

```
- [ X ] a bugfix
- [ ] a new feature
```

Checklist:

- [ X ] Changes are covered by unit tests
- [ X ] Code style is respected
- [ X ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ X ] CHANGELOG.md contains a short summary of the change
- [ X ] Documentation is updated as necessary

### Why this change is needed?
$worksheet->setCellValueByColumnAndRow(1,1,"123456\n");
Should add the value "123456\n" to the cell at indexes 1,1 but crashes because the DefaultValueBinder::dataTypeForValue matches (with the preg_match case) the value as a DataType::TYPE_NUMERIC and then the Cell->setValueExplicit crashes during the check if (is_string($pValue) && !is_numeric($pValue))

--
Thanks to [Vagir-dev](https://github.com/Vagir-dev) for help

Resolves #1476

### CODE REVIEW

**Comment by Vagir-dev** [comment]
Hi again :)

By the way, it is useful to mention related issues in the PR, like sescribed [here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).

**Comment by giannign1** [comment]
its mentioned in the title

maybe i did it wrong, sorry, this is the forst time for me

**Comment by Vagir-dev** [comment]
> its mentioned in the title

Just read this [article](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
 
> maybe i did it wrong, sorry, this is the forst time for me

That's why I gave you the hint ;)

**Comment by giannign1** [comment]
Thank you!
(tha manual why doesn't work for me :/ i used the automatic way)

**Comment by Vagir-dev** [comment]
I see you did all right! :) :+1:

**Comment by MarkBaker** [comment]
Thank you for providing the PR to resolve this issue.
Would it be possible to provide a unit test to "prove" the fix?

**Comment by MarkBaker** [comment]
Thanks

**Pull request merged**
