### PR TITLE
Removed leading slashes from migrator map

### PR DESCRIPTION
**Pull request by KacerCZ**
Fixes https://github.com/PHPOffice/PhpSpreadsheet/issues/245

### CODE REVIEW

**Comment by arturock** [comment]
Won't be better to use the `::class` constant?

**Comment by KacerCZ** [comment]
I don't think so, because migration uses simple string replacement (so any 'PHPExcel' string is replaced also in comments). After this fix I was able to successfuly use migration tool without any further modifications to class references.

**Comment by arturock** [comment]
I guess it may not be needed, but `::class` resolves to the same string than the hardcoded FQN without leading slash, however as the real class is being used it's safer and easier to spot any typo.

**Comment by PowerKiKi** [comment]
Thanks to both of for your contributions. I ended up going with `::class` notation.

**Comment by KacerCZ** [comment]
@arturock You are right, I didn't realize that `::class` returns class name without leading slash.

**Pull request closed without merging**
