### PR TITLE
Remove namespaces form Xlsx files

### PR DESCRIPTION
**Pull request by peterrehm**
This is:

- [X] a bugfix

Checklist:

- [ ] Changes are covered by unit tests
- [ ] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

What does it change?

I have ported the workaround from here: https://github.com/PHPOffice/PHPExcel/issues/1187#issuecomment-295032648

I have not added Tests as it seems the Xlsx Reader is currently not under test.

### CODE REVIEW

**Comment by PowerKiKi** [comment]
It is way too dangerous to `str_replace()` in strings that can contains user-generated content and thus this PR won't be merged as is. This should be done with real parsing of XML instead.

Would you be able to come up with a more robust `removeNamespaces()` method ?

**Comment by peterrehm** [comment]
Hm, what would you suggest? I just wanted to provide an option I do not know how commonly it is needed. 

It took me quit a while to figure out what is wrong and fortunately I found the above linked post.

**Comment by PowerKiKi** [comment]
I don't have a solution out of the box, but it should probably involve `simplexml` or `XMLReader`, or other robust XML libraries to avoid replacing user content by mistake.

**Comment by PowerKiKi** [comment]
I'll close it for now, not to give false hopes. But if a more robust solution appears, feel free to re-submit.

**Comment by xakepsoft** [comment]
Actually this is a safe and robust solution, a bit "hacky" though. Collision with user content is impossible because <CDATA is not allowed in XLSX files.  
This can be a viable solution until next major version of PhpSpreadsheet is released.

**Pull request closed without merging**
