### PR TITLE
Fix: Missing support for exotic names of excel-workbooks like "workbook2.xml"

### PR DESCRIPTION
**Pull request by rdoering**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [x] CHANGELOG.md contains a short summary of the change
- [x] Documentation is updated as necessary

### Why this change is needed?
Some auto generated xlsx files are using other names as workbook than "workbook.xml". This is fixed by supporting names of workbooks by regex `/workbook.*\.xml/`.

### CODE REVIEW

**Comment by rdoering** [comment]
Please write, if you have a question.

**Comment by rdoering** [comment]
Is here any progress?

**Comment by DraugDev** [comment]
Hay, when will it be merged? I would like to use it as soon as possible!

**Comment by rdoering** [comment]
Travis is only failing on PHP 7.4.

**Comment by rdoering** [comment]
Any news here?

**Comment by rdoering** [comment]
Is the addressed issue aleady fixed?

**Comment by PowerKiKi** [comment]
Yes, thanks to you. I merged your PR, with small adjustments, in https://github.com/PHPOffice/PhpSpreadsheet/commit/6a2e0cef4390c62e9847eaa09b1a2b48297d5651

**Pull request closed without merging**
