### PR TITLE
Workaround for Scrutinizer Initialization Problem

### LINKED ISSUE #2732: Scrutinizer is Broken
This is:

```
- [ ] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Scrutinizer should run correctly for each pull request/commit.

### What is the current behavior?
In the step "Compiling PHP runtime 8.1.1", the following error occurs:
```
configure: error: Package requirements (openssl >= 1.0.2) were not met:

Requested 'openssl >= 1.0.2' but version of OpenSSL is 1.0.1f
```
As a result, Scrutinizer terminates with "Test Setup Failed", and does not perform any analysis of the code. While we can still merge code despite such a failure, it would be better to have the Scrutinizer results available. I do not see any way to report this problem to the Scrutinizer folks.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

This has affected PRs #2728 (so April 4 is the approximate starting date for this problem), #2731, #2718, and #2723, and will presumably affect all future activity until the problem is resolved..

### Which versions of PhpSpreadsheet and PHP are affected?
Scrutinizer is attempting to set up PHP 8.1.1. The version of PhpSpreadsheet is irrelevant.

### PR DESCRIPTION
**Pull request by oleibman**
Fix #2732, which see for details. Solution suggested by @odan.

This is:

```
- [ ] a bugfix
- [ ] a new feature
- [x] Scrutinizer workaround
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [ ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### CODE REVIEW

**Comment by oleibman** [comment]
Failed twice now (with no real indication why), clearly too unstable to merge. Reverting to draft status, will continue to test periodically.

**Comment by MarkBaker** [comment]
@oleibman I'm planning to do a release tomorrow or Monday; is there anything that you especially want to push through into 1.23.0?

**Comment by oleibman** [comment]
@MarkBaker #2772 is probably ready. No strong feelings about whether it should or should not be in new release.

**Comment by oleibman** [comment]
Worked this time. Still took a very long (almost 10 minutes) to set up 8.1 environment. There are approximately as many new issues introduced (14) as existing issues fixed (15) since the last successful Scrutinizer run. Results haven't convinced me to merge this change, but I will continue to test.

**Comment by oleibman** [comment]
Still very slow. Complete in 18 minutes 44 seconds on 2022-08-14.

**Comment by oleibman** [comment]
Good results - down to 12 new issues (11 minor 1 unknown), with 57 issues fixed. Overall time still very long (over 20 minutes excluding almost 10 minutes in queue).

**Comment by oleibman** [comment]
Down to 4 new issues. Required only about 12 minutes.

**Comment by oleibman** [comment]
Scrutinizer appears to be working this morning (2022-09-12) without this override. I will monitor for a few days, and close this ticket if that continues to be the case.

**Comment by oleibman** [comment]
Issue appears resolved. Closing ticket.

**Pull request closed without merging**
