### PR TITLE
Fix #51: MATCH function behavior when third parameter is equal to 1 or -1

### LINKED ISSUE #51: Incorrect output for match function
Formula sample: `=MATCH(MAX({0,0,0,1,0,0,0,2,0,0,0,0,0,0,1,0,0}),{0,0,0,1,0,0,0,2,0,0,0,0,0,0,1,0,0})`

Code sample:

```php
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$spreadsheet->getActiveSheet()->setCellValue(
    'A1',
    '=MATCH(MAX({0,0,0,1,0,0,0,2,0,0,0,0,0,0,1,0,0}),{0,0,0,1,0,0,0,2,0,0,0,0,0,0,1,0,0})'
);
echo $spreadsheet->getActiveSheet()->getCell('A1')->getCalculatedValue();
```

This results to 4. The output i tested in excel, libreoffice calc and google sheets is 17.

### PR DESCRIPTION
**Pull request by agopaul**
This PR fixes https://github.com/PHPOffice/PhpSpreadsheet/issues/51.

### CODE REVIEW

**Comment by agopaul** [comment]
I'm not sure why the build crashed https://travis-ci.org/PHPOffice/PhpSpreadsheet/jobs/214412877#L8957, it seems like phpunit has seg faulted

**Comment by PowerKiKi** [comment]
I restarted Tavis build, we'll see what happens.

Were you able to confirm the implemented behavior in both Excel and LibreOffice ? (and maybe Google Spreadsheet ?)

**Comment by agopaul** [comment]
Yes, I created a reference file ([match.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/867231/match.xlsx)) with the same or similar cases in the tests and the results are identical to what Excel and LibreOffice returned.

As a side note, Google Spreadsheet has the same behavior of Excel, exception made for this case: `=MATCH(6, {3,5,6,8}, -1)`. For this one, I followed the Excel/LibreOffice implementation.

**Comment by PowerKiKi** [comment]
Great, thanks ! Just wanted to mention, in case you didn't stumble upon yet, that we have a `Functions::setCompatibilityMode(Functions::COMPATIBILITY_EXCEL);` thing that could be used in cases of different behaviors. But in this specific case I believe it is overkill and what you did should be fine.

Still not sure what's going on with Travis though... I've been running unit tests with coverage enabled locally but it's taking ages to complete...

**Comment by agopaul** [comment]
I tried running the same command locally and it works.

    $ ./vendor/bin/phpunit --debug --coverage-clover clover.xml
    ...
    Time: 8.53 minutes, Memory: 120.00MB

    OK, but incomplete, skipped, or risky tests!
    Tests: 4339, Assertions: 4710, Skipped: 1, Incomplete: 96.

    Generating code coverage report in Clover XML format ... done

PHP Version:

    $ php -v
    PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

Is there something that I can do to help?

**Comment by ankitm123** [comment]
@agopaul @PowerKiKi, I also ran it locally on my machine (php 7,1), and it did give me a segmentation fault.
php -version
PHP 7.1.3-2+deb.sury.org~xenial+1 (cli) (built: Mar 15 2017 09:21:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-2+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans

**Comment by PowerKiKi** [comment]
Merging because Travis failure is unrelated, thanks again !

**Comment by PowerKiKi** [comment]
As for the Travis failure, I was going to change the configuration to generate code coverage with PHP 7.0 instead of 7.1 as it seemed that 7.0 did not crash. However while I was doing I noticed that the issue actually disappeared by itself. I suppose Travis might have updated their env. But anyway, I didn't change anything after all.

**Pull request merged**
