### PR TITLE
Allow "Move but don't size with cells" to be set on images.

### PR DESCRIPTION
**Pull request by AdamGaskins**
This is:

```
- [ ] a bugfix
- [x] a new feature
```

Checklist:

- [ ] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [x] CHANGELOG.md contains a short summary of the change
- [x] Documentation is updated as necessary

### Why this change is needed?

See #1159 (and the abandoned PR #1160)

By default when adding a Drawing to a spreadsheet, it is added inside a `oneCellAnchor`. This makes it easier to specify a width and height, however in some cases developers may want to change the default value of the option pictured below in Excel. This PR allows developers to add images into spreadsheets with the setting "Move and size with cells."

image

Example use case: imagine a spreadsheet of product data where each row has a column called "Images." When a product row is deleted, it would make sense for the photo to be deleted as well. The only way for this to happen is to have "Move and size with cells" set.

All existing code will work the same, as `oneCellAnchor` remains the default. See `samples/Basic/47_Image_move_and_size_with_Cells.php` for an example of the new process using `twoCellAnchor`.
- Change the `Drawing` to `twoCellAnchor` mode.
- Specify the coordinates and offset as usual.
- Specify the coordinates and offset for the bottom right corner of the image using the new `setCoordinates2()`, `setOffsetX2()` and `setOffsetY2()` methods.
    - (`setWidth()` and `setHeight()` only work with `oneCellAnchor` mode)
- Add to the worksheet like normal

One other note: I also added `getImageWidth()` and `getImageHeight()` functions to drawing that return the original pixel width/height of the image. `getWidth()` and `getHeight()` contain this value when the image is initially loaded into the `Drawing`, but if you resize it in the worksheet this info is lost. Having these isn't necessary, but may be helpful due to the increased complexity of inserting images in `twoCellAnchor` mode.

### CODE REVIEW

**Review by PowerKiKi — CHANGES_REQUESTED** [review]
This looks like a nice improvement. There is a few things to improve though.

- the PR would need to be rebased on master
- unit tests are missing
- all new code must be type-hinted (not phpdoc-ed)
- parameters like `$pValue` should not be used anymore, instead use proper names, such as `$anchorType` and so on

**Comment by maximerenou** [comment]
Hello @AdamGaskins, are you still available to help on this feature? It would be a nice improvement.

**Comment by AdamGaskins** [comment]
Sure I can make the requested changes 👌🏻

**Comment by oleibman** [comment]
Superseded by PR #2532 and PR #2674.

**Pull request closed without merging**
