### PR TITLE
Better support of xlsm with forms

### PR DESCRIPTION
**Pull request by SailorMax**
This is:

```
- [x] a bugfix
- [x] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?
Collect some currently not supported features of Xlsx when document loaded. And restore them when same document saved. This allow to fill Xlsm templates, which has form elements, macros, printer settings, protected elements and back compatibility drawing, and save result without lost important elements of document.

### CODE REVIEW

**Comment by jbq** [comment]
I tried to incorporate this PR in my project because my form elements were discarded by PhpSpreadsheet, and now Excel crashes!

**Comment by SailorMax** [comment]
@jbq Can you share sample of your document? You can erase all private data from it.

**Comment by jbq** [comment]
@SailorMax Here are the details: https://www.dropbox.com/sh/xi9lrz42r8jctsd/AAAMCN0FanHKkVVFGrESFp2Za?dl=0

You will find the template XLSM file loaded by PhpSpreadsheet, and the one saved by the library with patch applied, without any extra processing.  The latter crashes Excel.

**Comment by SailorMax** [comment]
@jbq Looks like fixed. Can you check latest update?

**Comment by jbq** [comment]
@SailorMax sadly I had to quickly push to production and changed the form controls to plain cells with border styling to make it look like button, along with `BeforeDoubleClick` event handlers :-|  I like it even better than buttons :-)

**Comment by PowerKiKi** [comment]
thanks for the contribution, it's been merged with a few tweaks

**Pull request closed without merging**
