### PR TITLE
Xlsx Reader Better Namespace Handling Phase 1

### PR DESCRIPTION
**Pull request by oleibman**
There have been a number of issues concerning the handling of legitimate but unexpected namespace prefixes in Xlsx spreadsheets created by software other than Excel and PhpSpreadsheet/PhpExcel.I have studied them, but, till now, have not had a good idea on how to act on them. A recent comment https://github.com/PHPOffice/PhpSpreadsheet/issues/860#issuecomment-824926224 in issue #860 by @IMSoP has triggered an idea about how to proceed.

Gnumeric Reader was recently changed to handle namespaces better. Using that as a model, this PR begins the process of doing the same for Xlsx. Xlsx is much larger and more complicated than Gnumeric, hence the need to tackle it in multiple phases. I believe that this PR handles all of:
- listWorkSheetNames
- listWorkSheetInfo. Note that there was a bug in this function which would cause it to count only used columns rather than all columns. That bug is corrected.
- active sheet
- selected cell and top left cell
- cell content (formulas, numbers, text)
- hyperlinks
- comments (partial - see below)

This PR does not address:
- styles
- images and charts
- VBA and ribbons
- many other items, I'm sure

The issue for non-standard namespacing till now has been the use of unexpected prefixes. While I was working on this change, @Lambik introduced issue #2067 PR #2068 which introduced a completely different problem - the use of unexpected URLs. That PR and the issue associated with it were quite well documented, including the supplying of a test file and tests for it. I asked if I could take a look to see if it could be integrated with my change, and the result seems to be yes, so those changes are also part of this PR.

While adding a comment to my test file, I discovered that Microsoft had added "threaded comments" as a new feature. I believe these are not yet supported by PhpSpreadsheet, and I am not going to add it, at least not now. I believe that, among other things, this will make identifying the author of a comment more difficult.

Although there are a number of Phpstan baseline changes as part of this PR, I did not attempt to resolve all Phpstan reports for Reader/Xlsx. Nor did I do anything to increase coverage. This change is already large and complex enough without those efforts.

I will add more detail as comments after I push this change.

This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### CODE REVIEW

**Comment by oleibman** [comment]
The code responsible for the failing test is now fixed and the test is restored.

**Comment by MarkBaker** [comment]
Given the significance of this change, I'm not going to fully review/merge it until after the next release

**Comment by oleibman** [comment]
Seems right. I will leave it in draft status at least till then.

**Comment by oleibman** [comment]
If I can take this opportunity to ask a quick question unrelated to this change. Looking at the commits on May 11, there are two labeled with the original commit title, and described as "so-and-so authored and MarkBaker committed ...". On the same day, there is one labeled "merge pull request ... from so-and-so", and described as "oleibman committed ...". What should I be doing to get the label and description to look like yours?

**Comment by MarkBaker** [comment]
Good to see how well it works with the first Spreadsheet that I've tested it with

**Comment by oleibman** [comment]
Sigh of relief! Much better to have a "natural" example than the one I hand-crafted.

**Comment by MarkBaker** [comment]
re `"so-and-so authored and MarkBaker committed ..."` I had to rebase and merge, and that creates a new commit with my name tagged as a co-author.... sometimes I forget to remove that tag from the comments before pressing the button

**Comment by MarkBaker** [comment]
Now that 1.18.0 is released, I think we can continue work on this with a view to including it in the next release; I think it needs more extensive testing, particularly with real-world spreadsheet files, but from the few tests I've done, it looks pretty good so far

**Comment by oleibman** [comment]
@MarkBaker @PowerKiki - I require some help. I added two new spreadsheet and two new unit test members in response to Mark's latest comments. The unit tests did not proceed ("Waiting for status to be reported"). I was not able to resolve the differences in Github ("merge conflict between head and base"). The Github "Resolve conflicts" button is grayed out. I clicked on "Use the command line", which gives me the following information:

Conflicting files:
- src/PhpSpreadsheet/Reader/Xlsx.php
- src/PhpSpreadsheet/Reader/Xlsx/Properties.php
- tests/PhpSpreadsheetTests/Reader/SheetsXlsxChartTest.php
- tests/PhpSpreadsheetTests/Reader/XlsxTest.php

I believe the "tests" members are there because I earlier moved them out of the Reader directory into the Reader/Xlsx directory. I am satisfied with the contents of Xlsx.php and Xlsx/Properties.php.

```
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b oleibman-namexlsx master
git pull https://github.com/oleibman/PhpSpreadsheet.git namexlsx

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff oleibman-namexlsx
git push origin master
```

I have done the checkout and pull from Step 1, confirmed that the modules are as expected, and confirmed that the test suite runs without error. My repository says I have a branch named oleibman-namexlsx with no changes. So, I guess I'm ready to go on to the parts of "Step 2" above, but, having done nothing like that before, I need some reassurance that it's the right thing to do. I have captured all the output from my terminal session if you want me to upload it.

When I do all of that, is that just like a new push to namexlsx, or is it creating a new branch oleibman-namexlsx? Will the tests now run, or is there something else that will need to be done? Will the diff report for all the changes be meaningful? What else should I be looking out for?

**Comment by MarkBaker** [comment]
I'll take a look at lunchtime (CEST) but most of the merge conflicts seem to resolve around reading the date properties from the document, and a big conflict in XlsxTest.php

**Comment by MarkBaker** [comment]
Don't go ahead! Those merge conflicts need resolution first; I've tried manually resolving them once already, and ended up with a slew of errors. I'll have another go later, and try to identify what the actual problems are with the merge

**Comment by oleibman** [comment]
Yipe! I'm glad my call for help wasn't just because I was missing something blindingly obvious, but am sorry that this has become such a problem. If need be, I think I ought to be able to rebase and recreate this as a different PR - not my first choice, obviously, but possibly safer than trying to untangle everything.

**Comment by oleibman** [comment]
To help unravel things, I would like to open a separate PR to move SheetsXlsxChartTest and XlsxTest from Reader to Reader/Xlsx, with no other changes. It is really helpful to have all the Xlsx tests in the same directory. Do you think that would be okay, or would it mess things up even more?

**Comment by MarkBaker** [comment]
It seems sensible to move the Reader tests to the specific Reader/xxxx folders, and to maintain Readers just for generic IOFactory Reader testing (identify, etc)... and moving forward, I'm wanting to extract some of those reader tests for specific features (DataValidations, Conditional Formatting, etc) into their own test files as well.... so moving those two tests is a sensible idea

**Comment by oleibman** [comment]
I opened #2170, which is a pretty simple change, and it is also in "must resolve conflicts by hand" state. So I've converted it to a draft as well. I think I just need to start this over.

**Comment by oleibman** [comment]
Aha! Found the problem in 2170. It lacks the changes from #2149. I'll try to apply those and see what happens to it.

**Comment by oleibman** [comment]
Added the needed changes to 2170, but Github still thinks I need to do things by hand. Sigh.

**Comment by oleibman** [comment]
Trying test moves again as PR #2171. This seems to be more successful, and, if that holds, that will give me a new base to start from if need be.

**Comment by oleibman** [comment]
PR 2171 is ready to merge. If we haven't figured a way out of the mess in this PR by the start of next week, I will re-do it using 2171 as my starting point.

**Comment by oleibman** [comment]
Good news! I have been able to create a new branch combining 2171 and the changes in this PR, and it passes all the old and new unit tests, including the new spreadsheets added this week. Need to do a bit more testing, but expect a new PR early next week.

**Comment by oleibman** [comment]
Closing in favor of #2173.

**Pull request closed without merging**
