### PR TITLE
Chart: Correctly handle axis line styles

### PR DESCRIPTION
**Pull request by fox34**
Bugfix: Write line styles for y-axis of charts, not only x-axis, and read line styles for both axis.

This is:

```
- [X] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests
```

Checklist:

- [x] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [X] New unit tests have been added
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [X] CHANGELOG.md contains a short summary of the change
- [X] Documentation is updated as necessary

### Why this change is needed?

Line styles for y-axis could previously be set, but would not be saved to Xlsx files. Line styles for both x and y-axis were not read from Xlsx files.

### CODE REVIEW

**Comment by oleibman** [comment]
Can you add a unit test, or update a sample, to demonstrate that this situation was not handled correctly before and is handled correctly now?

**Comment by fox34** [comment]
Of course. Based on /samples/templates/chartSpreadsheet.php:

```php
<?php

use PhpOffice\PhpSpreadsheet\Chart\Axis;
use PhpOffice\PhpSpreadsheet\Chart\Chart;
use PhpOffice\PhpSpreadsheet\Chart\DataSeries;
use PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues;
use PhpOffice\PhpSpreadsheet\Chart\Legend as ChartLegend;
use PhpOffice\PhpSpreadsheet\Chart\PlotArea;
use PhpOffice\PhpSpreadsheet\Chart\Title;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as XlsxWriter;

// [...] Sample code from chartSpreadsheet.php omitted

// Create x- and y-axis
$xAxis = new Axis();
$xAxis->setLineColorProperties('FF0000');

$yAxis = new Axis();
$yAxis->setLineColorProperties('FF0000');

// Create the chart
$chart = new Chart(
    'chart1', // name
    $title, // title
    $legend, // legend
    $plotArea, // plotArea
    true, // plotVisibleOnly
    DataSeries::EMPTY_AS_GAP, // displayBlanksAs
    null, // xAxisLabel
    $yAxisLabel,  // yAxisLabel
    $xAxis,  // xAxis
    $yAxis   // yAxis
);

// Set the position where the chart should appear in the worksheet
$chart->setTopLeftPosition('A7');
$chart->setBottomRightPosition('H20');

// Add the chart to the worksheet
$worksheet->addChart($chart);

$writer = new XlsxWriter($spreadsheet);
$writer->setIncludeCharts(true);
$writer->save('out.xlsx');
```

Result before applying my patch:
grafik

Result after applying my patch:
grafik

**Comment by oleibman** [comment]
Please add that test/sample to your PR.

**Comment by fox34** [comment]
Done in https://github.com/PHPOffice/PhpSpreadsheet/pull/3163/commits/c2cdc36bb3145c763a173b5959a157440742b7f3.

**Comment by fox34** [comment]
Seems like the reader does not read line styles correctly, either. The resulting XLSX definitely contains the correct line styles.

**Comment by oleibman** [comment]
Thank you, that was exactly what I had in mind. Now I need to get a little nitpicky, and we should be ready to roll after that. Can you please set your axes to different colors in your test (e.g. set x-axis to 00FF00) so that the test shows that the correct style is applied to the correct axis.

**Comment by oleibman** [comment]
@MarkBaker @PowerKiKi This PR is ready but ... It still thinks the PHP 7.3 test is required, and so the "Squash and merge" button is grayed out for me. As a result, I don't know how to merge it.

**Comment by oleibman** [comment]
Thank you for your contribution.

**Pull request merged**
