### PR TITLE
Fix case where mergeComplexNumberFormatMasks would get stuck in endless-loop

### PR DESCRIPTION
**Pull request by brainz80**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?
In some cases PHPSpreadsheet would hang in ```mergeComplexNumberFormatMasks()``` because it was given a number with too many decimals. This fix will see to it that even if the loop -condition isn't satisfied the loop will end if ```$masks``` is empty.

### CODE REVIEW

**Comment by brainz80** [comment]
@MarkBaker Hi, mind checking this PR?

Been getting the follwing error until I made this fix.

```php
E_ERROR: Allowed memory size of 536870912 bytes exhausted (tried to allocate 536870920 bytes)
1  File "/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Style/NumberFormat.php" line 566
2  File "/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Style/NumberFormat.php" line 614 in PhpOffice\PhpSpreadsheet\Style\NumberFormat::mergeComplexNumberFormatMasks
3  File "/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Style/NumberFormat.php" line 651 in PhpOffice\PhpSpreadsheet\Style\NumberFormat::complexNumberFormatMask
4  File "/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Style/NumberFormat.php" line 714 in PhpOffice\PhpSpreadsheet\Style\NumberFormat::formatStraightNumericValue
5  File "/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Style/NumberFormat.php" line 861 in PhpOffice\PhpSpreadsheet\Style\NumberFormat::formatAsNumber
6  File "/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php" line 754 in PhpOffice\PhpSpreadsheet\Style\NumberFormat::toFormattedString
7  File "/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php" line 362 in PhpOffice\PhpSpreadsheet\Worksheet\Worksheet::calculateColumnWidths
8  File "/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php" line 64 in PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet::writeCols
9  File "/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php" line 274 in PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet::writeWorksheet
10 File "/var/www/html/v2/model/export.class.php" line 554 in PhpOffice\PhpSpreadsheet\Writer\Xlsx::save
11 File "/var/www/html/v2/model/export.class.php" line 179 in V2\Utils\Excel::output
12 File "/var/www/html/v2/controller/export/excel.ctrl.php" line 928 in V2\Utils\Excel::export
13 File "/var/www/html/model/system.class.php" line 301 in Dispatcher::
14 File "/var/www/html/index.php" line 293 in Dispatcher::dispatch
15 File "/var/www/html/index.php" line 0 in {main}

**Review by MarkBaker — CHANGES_REQUESTED** [review]
Can you provide a unit test to demonstrate that the issue is resolved by this fix?

**Comment by brainz80** [comment]
@MarkBaker I tried adding the following tests to the end of `tests\data\Style\NumberFormat.php`:

```php
    [
        'pfx. 25.00',
        25,
        '"pfx." 0.00;"pfx." -0.00;"pfx." 0.00;',
    ],
    [
        'pfx. 25.20',
        25.2,
        '"pfx." 0.00;"pfx." -0.00;"pfx." 0.00;',
    ],
    [
        'pfx. -25.20',
        -25.2,
        '"pfx." 0.00;"pfx." -0.00;"pfx." 0.00;',
    ],
    [
        'pfx. 25.26',
        25.255555555555555,
        '"pfx." 0.00;"pfx." -0.00;"pfx." 0.00;',
    ],
```

But doing this gave me errors when running phpunit. My guess is that the string prefix `"pfx."` is somehow handled wrong. But how that should be fixed I have no idea. Removing the dot from `"pfx."` lets me run through the tests without errors.

**Comment by brainz80** [comment]
I updated the pull-request with the Unit-tests and rebased the current `master` onto it.

**Comment by brainz80** [comment]
> @MarkBaker I tried adding the following tests to the end of `tests\data\Style\NumberFormat.php`:
> 
> ```
>     [
>         'pfx. 25.00',
>         25,
>         '"pfx." 0.00;"pfx." -0.00;"pfx." 0.00;',
>     ],
>     [
>         'pfx. 25.20',
>         25.2,
>         '"pfx." 0.00;"pfx." -0.00;"pfx." 0.00;',
>     ],
>     [
>         'pfx. -25.20',
>         -25.2,
>         '"pfx." 0.00;"pfx." -0.00;"pfx." 0.00;',
>     ],
>     [
>         'pfx. 25.26',
>         25.255555555555555,
>         '"pfx." 0.00;"pfx." -0.00;"pfx." 0.00;',
>     ],
> ```
> 
> But doing this gave me errors when running phpunit. My guess is that the string prefix `"pfx."` is somehow handled wrong. But how that should be fixed I have no idea. Removing the dot from `"pfx."` lets me run through the tests without errors.

The dot is handled wrongly also for suffixes `0.00_"sfx."`.

**Comment by MarkBaker** [comment]
I may have to take a closer look at the checks for a decimal point; because I suspect it's not ignoring a dot when it's wrapped in quotes; and that's probably what's throwing those tests

It's something I'll need to watch out for with something that I'm working on as well, numberFormatMask helpers/wizards; because I know at least one currency symbol that's letters followed by a dot (Danish Krone "kr.")

**Comment by MarkBaker** [comment]
Yes, I verified that there was a problem with number format masks containing a dot inside a quoted literal; and that's now been resolved in master; so if you rebase your branch from master and resubmit, then you shouldn't get those failing tests

**Comment by brainz80** [comment]
Yesh! Passed!

**Comment by MarkBaker** [comment]
Great, thanks for that

**Pull request merged**
