### PR TITLE
Fix for #1449 / Removing rows or columns that include range edges

### PR DESCRIPTION
**Pull request by jabouillei**
- [X] a bugfix
- [ ] a new feature

Checklist:

- [X] Changes are covered by unit tests
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?
Removing rows or columns that overlap the edge of a range should adjust the edges of the range.
Also, formulas in column A should be adjusted even if only 5 columns are being removed starting with column G. (A formula in column A may refer to a range that includes column G.)

### CODE REVIEW

**Comment by jabouillei** [comment]
I've started using the new version in our full environment and I'm having some troubles with named ranges and I don't know yet if it is because of going from 14.1 to 17.1 or because of my changes.  I'll look into this more in the coming 24 hours and comment again.

**Review by MarkBaker — COMMENTED** [review]
Is it possible to provide unit tests to prove that these changes actually work as expected. I know that the ReferenceHelper isn't well covered by unit tests at the moment; but this is quite a significant change, making it difficult to assess

**Comment by truthptn** [comment]
We've been using this patch for years. I do have a small unit test that I used to kick the tires when attempting to use 17.1.

```
<?php
require_once('PHPSpreadsheet/autoload.php');
require_once('PHPSpreadsheet/phpoffice/phpspreadsheet/src/PhpSpreadsheet/IOFactory.php');
$objReader = PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
$objReader->setIncludeCharts(true);
$content = $objReader->load('mergedtest2021.xlsx');
foreach ($content->getWorksheetIterator() as $worksheet) {
    $worksheet->removeColumn('F',4);
    //$worksheet->removeRow(3,3);
}
$objWriter = PhpOffice\PhpSpreadsheet\IOFactory::createWriter($content, 'Xlsx');
$objWriter->setPreCalculateFormulas(false);
$objWriter->setIncludeCharts(true);
$objWriter->save('mergedtest2021_after.xlsx');
?>
```
I suspect the "setIncludeCharts()" is not relevant and is just there because my original testing was with a client file that included charts and this test is based on the original test from when I first wrote the patch for PHPExcel.

Here is the simple little Excel file for use with the test case:
[mergedtest2021.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6738097/mergedtest2021.xlsx)

**Review by PowerKiKi — CHANGES_REQUESTED** [review]
This need to support PHP 8, pass CI and include at least some basic unit tests to be merged

**Comment by jabouillei** [comment]
I probably shouldn't have, but I laughed when I saw this.  The idea of updating a pull request that has been around this long to php 8!  I imagine someday I'd get an email requesting that it be updated to php10.  The bottom line is PHPSpreadsheet doesn't handle certain actions involving deleting rows and columns correctly and I fixed it years ago.  I fixed it as part of my job for Proposal Tech and made the fix available for the community years ago.  If the community would rather have the broken behavior, I wash my hands of it.
- Todd

    On Friday, October 29, 2021, 10:51:15 PM PDT, Adrien Crivelli ***@***.***> wrote:  
 
 


@PowerKiKi requested changes on this pull request.

This need to support PHP 8, pass CI and include at least some basic unit tests to be merged

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by oleibman** [comment]
Closing. Superseded by 3528.

**Pull request closed without merging**
