### PR TITLE
Apply Column and Row Styles to Existing Cells

### PR DESCRIPTION
**Pull request by oleibman**
This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [x] Documentation is updated as necessary

### Why this change is needed?

This is a fix for issue #1712.
When a style is applied to an entire row or column, it is currently
only effective for cells which don't already contain a value.
The code needs to iterate through existing cells in the row/column
in order to apply the style to them.
This could be considered a breaking change, however, I believe that
the change makes things operate as users would expect, and that the
existing implementation is incomplete.

The change also removes protected element conditionalStyles from
the Style class. That element is an unused remnant, and can no longer be
set or retrieved - methods getConditionalStyles and setConditionalStyles
actually act on an element in the Worksheet class.

Finally, additional tests are added so that Style, and in fact the
entire Style directory, now has 100% test coverage.

### CODE REVIEW

**Comment by oleibman** [comment]
There seems to be a problem with PHP8 tests on Web server - hangs after several thousand tests.  I don't have a problem with PHP8 on my own machine. So, converting to draft for now. Will open a new ticket to see if I can pinpoint the problem.

**Comment by oleibman** [comment]
Problem appears to be with PHP8 environment for PR. Opened issue #1725. Restoring status of this ticket from draft to "ready to review".

**Comment by MarkBaker** [comment]
The switch from travis CI to github actions may have a few teething issues, but was certainly necessary after travis dropped their OSS support earlier this week.

Thanks for all the work that you're contributing to the project; you're making an incredibly difference. I know you've done a lot with the calculation engine and formula as well, are you looking forward to implementing the new LAMBDA() and LET() functions in Excel as much as I am (not)?

**Comment by oleibman** [comment]
Glad to be of help. The LET and LAMBDA functions look fascinating. Alas, they seem too complicated for me to figure out how to implement them. I'll look forward to seeing how you do it.

**Pull request merged**
